### ISSUE TITLE
Since HA Core 2022.6.0 upgrade, landroid_cloud fails with missing attribute

### ISSUE THREAD

**Issue by gette** [MTrab/landroid_cloud#140]
### Environment:
 Home Assistant version: 2022.06.0
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
HACS v1.25.5
Running on Hassio OS on RPI4
Landroid_cloud version: 2.0.2
-->

## Configuration

```yaml
#landroid_cloud:
#  - email: *****@gmail.com
#    password: !secret landroid_secret

```

## Describe the bug
after upgrade and first reboot, everything works fine,
but if i don't comment the yaml configuration i got an validation error

***
Package landroid setup failed. Component landroid_cloud cannot be merged. Dict expected in main config.
***

## Debug log

```Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Source: custom_components/landroid_cloud/config_flow.py:50
Integration: Landroid Cloud (documentation, issues)
First occurred: 10:12:08 (2 occurrences)
Last logged: 10:12:08

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/landroid_cloud/config_flow.py", line 90, in async_step_import
    if self.check_for_existing(import_config):
  File "/config/custom_components/landroid_cloud/config_flow.py", line 49, in check_for_existing
    return any(
  File "/config/custom_components/landroid_cloud/config_flow.py", line 50, in <genexpr>
    entry.data.get(CONF_EMAIL) == data.get(CONF_EMAIL)
AttributeError: 'str' object has no attribute 'get'


```

**Comment by MTrab** [comment]
Your debug log doesn't indicate a missing dict.
It indicates that the yaml-config you have refrerenced isn't the one you are using in your config.
Remember the little **-** before email.

Or even better - remove the landroid_cloud config from your configuration.yaml and add your Landroid via the new integration flow in GUI.

**Comment by MTrab** [comment]
Just to be clear - you have used the integration flow, and don't have any landroid_cloud in your YAML config?

**Comment by gette** [comment]
> Just to be clear - you have used the integration flow, and don't have any landroid_cloud in your YAML config?

yup, nothing in the yaml config now

**Comment by gette** [comment]
following errors
don't know if they are related


```
Logger: homeassistant.helpers.event
Source: helpers/template.py:411
First occurred: 12:10:48 (10 occurrences)
Last logged: 12:10:48

Error while processing template: Template("{% set strength = state_attr('sensor.landroid_john_status', 'rssi') | float -%} {%- if strength > -56 -%}mdi:wifi-strength-4 {% elif strength > -67 -%}mdi:wifi-strength-3 {% elif strength > -78 -%}mdi:wifi-strength-2 {% elif strength > -89 -%}mdi:wifi-strength-1 {%- else -%}mdi:wifi-strength-outline {%- endif %}")
Error while processing template: Template("{{ (states('sensor.energiemonitor_channel_a_power')|float + states('sensor.energiemonitor_channel_b_power')|float + states('sensor.energiemonitor_channel_c_power')|float) }}")
Error while processing template: Template("{% if states('sensor.power_total')|float < 0 %} 0 {% else %} {{ states('sensor.power_total') }} {% endif %}")
Error while processing template: Template("{% if states('sensor.power_total')|float < 0 %} {{ (states('sensor.power_total')|float * (-1)|float) }} {% else %} 0 {% endif %}")
Error while processing template: Template("{{ (states('sensor.power_total')|float + states('sensor.solaredge_current_power')|float) }}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1615, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 409, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1842, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1618, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1331, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set level = states('sensor.landroid_john_battery') | float -%} {%- if is_state_attr('sensor.landroid_john_battery', 'charging', 1) -%}
  {%- if level > 99 -%}mdi:battery-charging-100
  {%- elif level > 89 -%}mdi:battery-charging-90
  {%- elif level > 79 -%}mdi:battery-charging-80
  {%- elif level > 69 -%}mdi:battery-charging-70
  {%- elif level > 59 -%}mdi:battery-charging-60
  {%- elif level > 49 -%}mdi:battery-charging-50
  {%- elif level > 39 -%}mdi:battery-charging-40
  {%- elif level > 29 -%}mdi:battery-charging-30
  {%- elif level > 19 -%}mdi:battery-charging-20
  {%- elif level > 9 -%}mdi:battery-charging-10
  {%- else -%}mdi:battery-charging-outline
  {%- endif -%}
{%- else -%}
  {%- if level > 99 -%}mdi:battery
  {%- elif level > 89 -%}mdi:battery-90
  {%- elif level > 79 -%}mdi:battery-80
  {%- elif level > 69 -%}mdi:battery-70
  {%- elif level > 59 -%}mdi:battery-60
  {%- elif level > 49 -%}mdi:battery-50
  {%- elif level > 39 -%}mdi:battery-40
  {%- elif level > 29 -%}mdi:battery-30
  {%- elif level > 19 -%}mdi:battery-20
  {%- elif level > 9 -%}mdi:battery-10
  {%- else -%}mdi:battery-outline
  {%- endif -%}
{%- endif %}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 525, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 411, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set level = states('sensor.landroid_john_battery') | float -%} {%- if is_state_attr('sensor.landroid_john_battery', 'charging', 1) -%}
  {%- if level > 99 -%}mdi:battery-charging-100
  {%- elif level > 89 -%}mdi:battery-charging-90
  {%- elif level > 79 -%}mdi:battery-charging-80
  {%- elif level > 69 -%}mdi:battery-charging-70
  {%- elif level > 59 -%}mdi:battery-charging-60
  {%- elif level > 49 -%}mdi:battery-charging-50
  {%- elif level > 39 -%}mdi:battery-charging-40
  {%- elif level > 29 -%}mdi:battery-charging-30
  {%- elif level > 19 -%}mdi:battery-charging-20
  {%- elif level > 9 -%}mdi:battery-charging-10
  {%- else -%}mdi:battery-charging-outline
  {%- endif -%}
{%- else -%}
  {%- if level > 99 -%}mdi:battery
  {%- elif level > 89 -%}mdi:battery-90
  {%- elif level > 79 -%}mdi:battery-80
  {%- elif level > 69 -%}mdi:battery-70
  {%- elif level > 59 -%}mdi:battery-60
  {%- elif level > 49 -%}mdi:battery-50
  {%- elif level > 39 -%}mdi:battery-40
  {%- elif level > 29 -%}mdi:battery-30
  {%- elif level > 19 -%}mdi:battery-20
  {%- elif level > 9 -%}mdi:battery-10
  {%- else -%}mdi:battery-outline
  {%- endif -%}
{%- endif %}' but no default was specified

```
and also
```
Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:173
Integration: Template (documentation, issues)
First occurred: 12:10:48 (10 occurrences)
Last logged: 12:10:48

TemplateError('ValueError: Template error: float got invalid input 'None' when rendering template '{% set strength = state_attr('sensor.landroid_john_status', 'rssi') | float -%} {%- if strength > -56 -%}mdi:wifi-strength-4 {% elif strength > -67 -%}mdi:wifi-strength-3 {% elif strength > -78 -%}mdi:wifi-strength-2 {% elif strength > -89 -%}mdi:wifi-strength-1 {%- else -%}mdi:wifi-strength-outline {%- endif %}' but no default was specified') while processing template 'Template("{% set strength = state_attr('sensor.landroid_john_status', 'rssi') | float -%} {%- if strength > -56 -%}mdi:wifi-strength-4 {% elif strength > -67 -%}mdi:wifi-strength-3 {% elif strength > -78 -%}mdi:wifi-strength-2 {% elif strength > -89 -%}mdi:wifi-strength-1 {%- else -%}mdi:wifi-strength-outline {%- endif %}")' for attribute '_attr_icon' in entity 'sensor.landroid_wifi'
TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.energiemonitor_channel_a_power')|float + states('sensor.energiemonitor_channel_b_power')|float + states('sensor.energiemonitor_channel_c_power')|float) }}' but no default was specified') while processing template 'Template("{{ (states('sensor.energiemonitor_channel_a_power')|float + states('sensor.energiemonitor_channel_b_power')|float + states('sensor.energiemonitor_channel_c_power')|float) }}")' for attribute '_attr_native_value' in entity 'sensor.power_total'
TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% if states('sensor.power_total')|float < 0 %} 0 {% else %} {{ states('sensor.power_total') }} {% endif %}' but no default was specified') while processing template 'Template("{% if states('sensor.power_total')|float < 0 %} 0 {% else %} {{ states('sensor.power_total') }} {% endif %}")' for attribute '_attr_native_value' in entity 'sensor.power_total_grid'
TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% if states('sensor.power_total')|float < 0 %} {{ (states('sensor.power_total')|float * (-1)|float) }} {% else %} 0 {% endif %}' but no default was specified') while processing template 'Template("{% if states('sensor.power_total')|float < 0 %} {{ (states('sensor.power_total')|float * (-1)|float) }} {% else %} 0 {% endif %}")' for attribute '_attr_native_value' in entity 'sensor.power_total_returned'
TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states('sensor.power_total')|float + states('sensor.solaredge_current_power')|float) }}' but no default was specified') while processing template 'Template("{{ (states('sensor.power_total')|float + states('sensor.solaredge_current_power')|float) }}")' for attribute '_attr_native_value' in entity 'sensor.power_total_home'
```

**Comment by MTrab** [comment]
Those errors are related to the fact that landroid integration have moved to vacuum platform rather than sensor platform. So the sensors you are referring to are no longer available.
