### ISSUE TITLE
Is scan_interval required in config?

### ISSUE THREAD

**Issue by Barma-lej** [MTrab/landroid_cloud#15]
Home Assistant Core 0.108.9
landroid_cloud 1.3.2 and 1.3.3
Log:
`Invalid config for [landroid_cloud]: invalid boolean value 0:00:30 for dictionary value @ data['landroid_cloud']['scan_interval']. Got None. (See ?, line ?).`
If i write to config `scan_interval: 10` then there is no error. But what is for unit of measurement of interval? Seconds? Minutes?

After restart HA reports that:
```
Invalid config
The following integrations and platforms could not be set up:

landroid_cloud
Please check your config.
```

Then i delete  `scan_interval: 10` from config and restart HA and getting again: 
```
Invalid config
The following integrations and platforms could not be set up:

landroid_cloud
Please check your config.
```
In config:
```
landroid_cloud:
  email: mail@mail.com
  password: pass
```
In log:
```
Logger: homeassistant.setup
Source: custom_components/landroid_cloud/__init__.py:96
First occurred: 14:37:25 (1 occurrences)
Last logged: 14:37:25

Error during setup of component landroid_cloud
Traceback (most recent call last):
  File "/home/pi/hass/lib/python3.7/site-packages/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/home/pi/.homeassistant/custom_components/landroid_cloud/__init__.py", line 96, in async_setup
    refresh_rate = timedelta(seconds=config[DOMAIN][CONF_SCAN_INTERVAL])
KeyError: 'scan_interval'
```

**Comment by Barma-lej** [comment]
After restart HA reports that:
```
Invalid config
The following integrations and platforms could not be set up:

landroid_cloud
Please check your config.
```

**Comment by MTrab** [comment]
That was an error - please update to latest release where this was fixed.
