### ISSUE TITLE
Functions "start mowing" or "go home" not working after upgrade to 2.0.3

### ISSUE THREAD

**Issue by tomzi007** [MTrab/landroid_cloud#162]
I have lost most of functionality for my Worx mower after upgrade.
Product Code: WR101SI

Before I was able to use service e.g. "start mowing" or "go home". Now these two are gone. 
How can I use those two with new update?

If I run 
service: landroid_cloud.ots
data:
  runtime: 60
target:
  device_id: xxxxx

this error pops up: 

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/landroid_cloud/devices/worx.py:109
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:34:32 PM (1 occurrences)
Last logged: 8:34:32 PM

[548224249664] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 636, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 697, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/landroid_cloud/devices/worx.py", line 109, in async_ots
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 475, in ots
    raise NoOneTimeScheduleError(
pyworxcloud.exceptions.NoOneTimeScheduleError: This device does not support Edgecut-on-demand

**Comment by MTrab** [comment]
As the error says:
pyworxcloud.exceptions.NoOneTimeScheduleError: This device does not support Edgecut-on-demand

As for the services, they follow the vacuum domain design for the standard start/stop commands (vacuum.*) as the integration have moved to the vacuum design

**Comment by tomzi007** [comment]
Thank you! I haven't realized vacuum commands till now.
