### ISSUE TITLE
Error on restart after upgrade to v2.1.0

### ISSUE THREAD

**Issue by tbergo** [MTrab/landroid_cloud#167]
## Describe the bug
Error after upgrade to v2.1.0.
Setup failed for custom integration landroid_cloud: Unable to import component: Exception importing custom_components.landroid_cloud

## Debug log

```text

Logger: homeassistant.loader
Source: custom_components/landroid_cloud/__init__.py:10
Integration: Landroid Cloud ([documentation](https://github.com/MTrab/landroid_cloud/blob/master/README.md), [issues](https://github.com/MTrab/landroid_cloud/issues))
First occurred: 22:43:07 (1 occurrences)
Last logged: 22:43:07

Unexpected exception importing component custom_components.landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/landroid_cloud/__init__.py", line 10, in <module>
    from pyworxcloud import WorxCloud, exceptions
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 24, in <module>
    from .utils import (
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/__init__.py", line 7, in <module>
    from .location import Location
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/location.py", line 6, in <module>
    class Location(LDict):
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/location.py", line 9, in Location
    def __init__(self, latitude: float | None = None, longitude: float | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

```

**Comment by Barma-lej** [comment]
To @MTrab 

`|` was added in python 3.10, so not available in python 3.9.2 which used in Home Assistant Supervised core-2022.6.7

For example in file `device_base.py` lines 116 - 118
```
    _battery_level: int | None = None
    _attr_state = STATE_INITIALIZING
    _attr_landroid_features: int | None = None
```

You can try to use string for type annotation:
```
    _battery_level: "int | None" = None
    _attr_state = STATE_INITIALIZING
    _attr_landroid_features: "int | None" = None
```

**Comment by arcano81** [comment]
Same issue here!

**Comment by gordenfalk** [comment]
Same issue here!

**Comment by Subbilein** [comment]
Same here

**Comment by MTrab** [comment]
> `|` was added in python 3.10, so not available in python 3.9.2 which is using in Home Assistant Supervised core-2022.6.7

So much for trying to keep my dev containers at same level as Home Assistant, along side my day job which requires another level of patching 😄 Thanks for the heads-up. Will release a v3.9 compatible version during today.

**Comment by MTrab** [comment]
Arh - now I see why I haven't encountered this error myself.
Ludeeus devcontainer (ghcr.io/ludeeus/devcontainer/integration) which I use, uses Python 3.10 for some reason 🙁

**Comment by Subbilein** [comment]
No Problem. 
at this point, I‘d like to say thank you for your very good integration and the perfect support. 
Guys like you make HomeAssistant to such a big thing!
Thanks a lot!
