### ISSUE TITLE
Failed to set up (start)

### ISSUE THREAD

**Issue by larronni** [MTrab/landroid_cloud#169]
## Environment:

- Home Assistant version: 2022.6.7
- Landroid_cloud version: 2.1.1

## Describe the bug
Error setting up entry Worx -  for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 61, in async_setup_entry
    result = await _setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 203, in _setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 224, in connect
    self._fetch()
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 609, in _fetch
    device = DeviceHandler(self._api, product)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/devices.py", line 36, in __init__
    self.__mapinfo(api, product)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/devices.py", line 75, in __mapinfo
    self.blades = Blades(data)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/blades.py", line 31, in __init__
    self["reset_at"] = int(data["blade_work_time_reset"])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by cryd-s** [comment]
Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:203
Integration: Landroid Cloud ([documentation](https://github.com/MTrab/landroid_cloud/blob/master/README.md), [issues](https://github.com/MTrab/landroid_cloud/issues))
First occurred: 14:09:11 (1 occurrences)
Last logged: 14:09:11

Error setting up entry Worx - manuel.fichtner@me.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 61, in async_setup_entry
    result = await _setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 203, in _setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 224, in connect
    self._fetch()
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 609, in _fetch
    device = DeviceHandler(self._api, product)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/devices.py", line 36, in __init__
    self.__mapinfo(api, product)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/devices.py", line 84, in __mapinfo
    self.warranty = Warranty(data)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/warranty.py", line 20, in __init__
    self["expires_at"] = string_to_time(
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/helpers/time_format.py", line 38, in string_to_time
    datetime.strptime(dt_string, format)
TypeError: strptime() argument 1 must be str, not None
