### ISSUE TITLE
str, not None

### ISSUE THREAD

**Issue by teshiburu2020** [MTrab/landroid_cloud#172]
Error in version following upgrade from 2.1.0 to 2.1.1 below is environment and current error message 

### Environment:

- Home Assistant version: 2022.6.7
- Landroid_cloud version: 2.1.1
- Operation system: Unraid Docker - HA Core

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 61, in async_setup_entry
    result = await _setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 203, in _setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 224, in connect
    self._fetch()
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 609, in _fetch
    device = DeviceHandler(self._api, product)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/devices.py", line 36, in __init__
    self.__mapinfo(api, product)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/devices.py", line 84, in __mapinfo
    self.warranty = Warranty(data)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/warranty.py", line 20, in __init__
    self["expires_at"] = string_to_time(
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/helpers/time_format.py", line 38, in string_to_time
    datetime.strptime(dt_string, format)
TypeError: strptime() argument 1 must be str, not None

```

**Comment by teshiburu2020** [comment]
Ignore this, the error message has now changed following the upgrade from 2.1.1 to 2.1.2 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 61, in async_setup_entry
    result = await _setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 203, in _setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 224, in connect
    self._fetch()
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 609, in _fetch
    device = DeviceHandler(self._api, product)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/devices.py", line 36, in __init__
    self.__mapinfo(api, product)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/devices.py", line 84, in __mapinfo
    self.warranty = Warranty(data)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/warranty.py", line 25, in __init__
    self["expires_at"]
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
```
