### ISSUE TITLE
error after update to new version 

### ISSUE THREAD

**Issue by flatty2804** [MTrab/landroid_cloud#176]
The system cannot restart because the configuration is not valid: Component error: landroid_cloud - Exception importing custom_components.landroid_cloud

now i cannot restart anymore

**Comment by MTrab** [comment]
And what does your log say?

**Comment by r100gs** [comment]
Same here
Component error: landroid_cloud - Exception importing custom_components.landroid_cloud

`````
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.loader
Source: custom_components/landroid_cloud/__init__.py:13
Integration: landroid_cloud (documentation, issues)
First occurred: 07:00:32 (5 occurrences)
Last logged: 07:03:47

Unexpected exception importing component custom_components.landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/landroid_cloud/__init__.py", line 13, in <module>
    from pyworxcloud import WorxCloud
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 24, in <module>
    from .utils import (
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/__init__.py", line 7, in <module>
    from .location import Location
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/location.py", line 6, in <module>
    class Location(LDict):
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/location.py", line 9, in Location
    def __init__(self, latitude: float | None = None, longitude: float | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
`````
here

`````
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:684
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 07:01:14 (1 occurrences)
Last logged: 07:01:14

[140674222538272] The system cannot restart because the configuration is not valid: Component error: landroid_cloud - Exception importing custom_components.landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 684, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: landroid_cloud - Exception importing custom_components.landroid_cloud

```

**Comment by flatty2804** [comment]
Von meinem iPhone gesendet

**Comment by kepath** [comment]
I get a very similar error to that above

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:203 
Integration: Landroid Cloud (documentation, issues) 
First occurred: 8:17:32 AM (1 occurrences) 
Last logged: 8:17:32 AM

Error setting up entry Worx - worx.com@kevinthorn.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 61, in async_setup_entry
    result = await _setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 203, in _setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 224, in connect
    self._fetch()
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 609, in _fetch
    device = DeviceHandler(self._api, product)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/devices.py", line 36, in __init__
    self.__mapinfo(api, product)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/devices.py", line 84, in __mapinfo
    self.warranty = Warranty(data)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/warranty.py", line 25, in __init__
    self["expires_at"]
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
```

**Comment by MTrab** [comment]
@flatty2804 is this the same error as @r100gs that you have?
