### ISSUE TITLE
Cannot restart 2.1.3

### ISSUE THREAD

**Issue by vekexasia** [MTrab/landroid_cloud#184]
I get Component landroid_cloud Exception importing custom_components.landroid_cloud

this is the log
```
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/landroid_cloud/__init__.py:10
Integration: Landroid Cloud (documentation, issues)
First occurred: 10:49:42 AM (3 occurrences)
Last logged: 10:52:27 AM

Unexpected exception importing component custom_components.landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/landroid_cloud/__init__.py", line 10, in <module>
    from pyworxcloud import WorxCloud, exceptions
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 24, in <module>
    from .utils import (
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/__init__.py", line 7, in <module>
    from .location import Location
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/location.py", line 6, in <module>
    class Location(LDict):
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/utils/location.py", line 9, in Location
    def __init__(self, latitude: float | None = None, longitude: float | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

```

**Comment by vekexasia** [comment]
Fixed by removing rebooting and reinstalling :)

**Comment by MTrab** [comment]
I was just about to say, that this couldn't be on 2.1.3, as this issue was fixed in a prior release ;)
