### ISSUE TITLE
Error with Landroid

### ISSUE THREAD

**Issue by KHOne23** [MTrab/landroid_cloud#195]
## Configuration

```yaml

Add your YAML configuration here.

config via Web Config

## Describe the bug
Integration don´t work since 2022.07.0. I also tryed to delete Landroid from App an reconfigure but this changed nothing.

## Debug log

<!-- To enable debug logs check this https://www.home-assistant.io/components/logger/ -->

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/api.py:60
Integration: Landroid Cloud ([documentation](https://github.com/MTrab/landroid_cloud/blob/master/README.md), [issues](https://github.com/MTrab/landroid_cloud/issues))
First occurred: 18:42:51 (1 occurrences)
Last logged: 18:42:51

Error setting up entry Worx - k.heimers@gmx.de for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 217, in _async_setup
    await asyncio.gather(
  File "/config/custom_components/landroid_cloud/__init__.py", line 235, in async_init_device
    api = LandroidAPI(hass, name, entry)
  File "/config/custom_components/landroid_cloud/api.py", line 60, in __init__
    self.cloud.set_callback(LandroidEvent.MQTT_RATELIMIT, self._on_ratelimit)
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: MQTT_RATELIMIT
```

**Comment by KHOne23** [comment]
works with Beta 2.1.5
