### ISSUE TITLE
Ladroid doesn't appear in Landroid_cloud version: 2.3.0

### ISSUE THREAD

**Issue by Barma-lej** [MTrab/landroid_cloud#235]
## Screenshot

![mower2](https://user-images.githubusercontent.com/34010886/180249919-2d60cafb-f8e8-41fb-bebc-423701952a4a.png)

## Describe the bug

Ladroid doesn't appear in Landroid_cloud version: 2.3.0

## Debug log

```text
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:330
First occurred: 17:06:14 (1 occurrences)
Last logged: 17:06:14

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 363, in _forward_on_message
    self._decode_data(device)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 556, in _decode_data
    device.schedules.update_progress_and_next(
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/schedules.py", line 196, in update_progress_and_next
    self["daily_progress"] = info.calculate_progress()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/schedules.py", line 114, in calculate_progress
    if self.__now >= start and self.__now < end:
TypeError: can't compare offset-naive and offset-aware datetimes
```

## Attributes
```
Accessories
—
Battery
cycles:
total: 0
current: 0
reset_at: null
reset_time: null
Blades
total_on: 74432
reset_at: 61657
reset_time: '2022-04-19T07:04:53+02:00'
current_on: 12775
Error
id: -1
description: unknown
Firmware
auto_upgrade: false
version: 3.26
Locked
false
MAC address
98D863343CEC
Model
Landroid M500
Online
true
Orientation
pitch: 0
roll: 0
yaw: 0
Rain sensor
delay: 0
Schedule
time_extension: 0
active: true
auto_schedule:
settings: {}
enabled: null
Serial number
20193019840101487912
Status info
id: -1
description: unknown
Time zone
Europe/Berlin
Zone
current: null
next: null
index: null
indicies:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
starting_point:
- 0
- 0
- 0
- 0
Capabilities
—
Mqtt connected
true
Supported landroid features
0
Daily progress
—
Next scheduled start
—
```

**Comment by tlm4594** [comment]
Just updated and I'm having the same issue on a W147. Stuck in "initializing".
