### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by yolani** [MTrab/landroid_cloud#236]
Since upgrading to 2.3.0, the statistics attribute in HA is gone, which used to contain 'distance', 'total_worktime' and others. Is that intended?

**Comment by yolani** [comment]
Not on my end ;-)

Anyway, I think there might be an issue... My landroid is working fine with the official app, but the state in HA is stuck at "initializing".

Also I found this exception which occurs at every startup / integration reload.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 363, in _forward_on_message
    self._decode_data(device)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 556, in _decode_data
    device.schedules.update_progress_and_next(
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/schedules.py", line 196, in update_progress_and_next
    self["daily_progress"] = info.calculate_progress()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/schedules.py", line 114, in calculate_progress
    if self.__now >= start and self.__now < end:
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by MTrab** [comment]
Okay - that relates to this issue then: https://github.com/MTrab/pyworxcloud/issues/76

Fix is on the way - just doing a little housekeeping in code snips that's no longer in use before releasing the fix
