### ISSUE TITLE
Porblme with refresh device

### ISSUE THREAD

**Issue by maury77** [MTrab/landroid_cloud#240]
### Environment:

- Home Assistant version: 2022.7.6
- Landroid_cloud version: 2.3.1
- Operation system: raspian

## Describe the bug

The plugin not refresh status of device

If I force reload the error is

2022-07-23 13:06:50 WARNING (MainThread) [custom_components.landroid_cloud.device_base] (leonardo, Update signal) MQTT connection is offline, scheduling Web API refresh in 15 minutes. Device is in readonly mode!
2022-07-23 13:06:51 ERROR (Thread-111) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/homeassistant/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 363, in _forward_on_message
    self._decode_data(device)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 556, in _decode_data
    device.schedules.update_progress_and_next(
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/pyworxcloud/utils/schedules.py", line 196, in update_progress_and_next
    self["daily_progress"] = info.calculate_progress()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/pyworxcloud/utils/schedules.py", line 114, in calculate_progress
    if self.__now >= start and self.__now < end:

**Comment by MTrab** [comment]
Thanks for reporting.
This will be ULTRA low priority, as it should NEVER be called ;)
It's only there as a LAST resort.

**Comment by maury77** [comment]
the problem that never refresh after restarting the device with last version, the forcing was just a test

**Comment by maury77** [comment]
I try rollback the to library pyworxcloud==2.1.8' and the problem is not present

**Comment by MTrab** [comment]
Refreshes happens when the device sends new data to the server - hence, the refresh are actually only there for debugging purposes and might disappear again.
DO NOT build your code around requiring that service!!
