### ISSUE TITLE
Sensors disappeared since update to 2.3.1

### ISSUE THREAD

**Issue by bommel947** [MTrab/landroid_cloud#242]
## Environment:
- Home Assistant version: 2022.7.1
- Landroid_cloud version: 2.3.1
- Operation system: HAOS 8.4
- Mower: WORX WR105SI.1

## Describe the bug
Since the update to 2.3.1 all sensors from the mower are gone :-(
A lot of errors appeared! See below.

## Debug log

-------------------------------------------------------------------
Landroid Cloud integration

Version: 2.3.1
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/mtrab/landroid_cloud/issues
-------------------------------------------------------------------

2022-08-03 22:16:05 INFO (MainThread) [homeassistant.setup] Setting up upnp
2022-08-03 22:16:05 INFO (MainThread) [homeassistant.setup] Setup of domain upnp took 0.0 seconds

2022-08-03 22:16:25 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{% set level = states('sensor.landroid_mower_battery') | float -%} {%- if is_state_attr('sensor.landroid_mower_battery', 'charging', 1) -%}
  {%- if level > 99 -%}mdi:battery-charging-100
  {%- elif level > 89 -%}mdi:battery-charging-90
  {%- elif level > 79 -%}mdi:battery-charging-80
  {%- elif level > 69 -%}mdi:battery-charging-70
  {%- elif level > 59 -%}mdi:battery-charging-60
  {%- elif level > 49 -%}mdi:battery-charging-50
  {%- elif level > 39 -%}mdi:battery-charging-40
  {%- elif level > 29 -%}mdi:battery-charging-30
  {%- elif level > 19 -%}mdi:battery-charging-20
  {%- elif level > 9 -%}mdi:battery-charging-10
  {%- else -%}mdi:battery-charging-outline
  {%- endif -%}
{%- else -%}
  {%- if level > 99 -%}mdi:battery
  {%- elif level > 89 -%}mdi:battery-90
  {%- elif level > 79 -%}mdi:battery-80
  {%- elif level > 69 -%}mdi:battery-70
  {%- elif level > 59 -%}mdi:battery-60
  {%- elif level > 49 -%}mdi:battery-50
  {%- elif level > 39 -%}mdi:battery-40
  {%- elif level > 29 -%}mdi:battery-30
  {%- elif level > 19 -%}mdi:battery-20
  {%- elif level > 9 -%}mdi:battery-10
  {%- else -%}mdi:battery-outline
  {%- endif -%}
{%- endif %}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1679, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 421, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1906, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1682, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1395, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set level = states('sensor.landroid_mower_battery') | float -%} {%- if is_state_attr('sensor.landroid_mower_battery', 'charging', 1) -%}
  {%- if level > 99 -%}mdi:battery-charging-100
  {%- elif level > 89 -%}mdi:battery-charging-90
  {%- elif level > 79 -%}mdi:battery-charging-80
  {%- elif level > 69 -%}mdi:battery-charging-70
  {%- elif level > 59 -%}mdi:battery-charging-60
  {%- elif level > 49 -%}mdi:battery-charging-50
  {%- elif level > 39 -%}mdi:battery-charging-40
  {%- elif level > 29 -%}mdi:battery-charging-30
  {%- elif level > 19 -%}mdi:battery-charging-20
  {%- elif level > 9 -%}mdi:battery-charging-10
  {%- else -%}mdi:battery-charging-outline
  {%- endif -%}
{%- else -%}
  {%- if level > 99 -%}mdi:battery
  {%- elif level > 89 -%}mdi:battery-90
  {%- elif level > 79 -%}mdi:battery-80
  {%- elif level > 69 -%}mdi:battery-70
  {%- elif level > 59 -%}mdi:battery-60
  {%- elif level > 49 -%}mdi:battery-50
  {%- elif level > 39 -%}mdi:battery-40
  {%- elif level > 29 -%}mdi:battery-30
  {%- elif level > 19 -%}mdi:battery-20
  {%- elif level > 9 -%}mdi:battery-10
  {%- else -%}mdi:battery-outline
  {%- endif -%}
{%- endif %}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 537, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set level = states('sensor.landroid_mower_battery') | float -%} {%- if is_state_attr('sensor.landroid_mower_battery', 'charging', 1) -%}
  {%- if level > 99 -%}mdi:battery-charging-100
  {%- elif level > 89 -%}mdi:battery-charging-90
  {%- elif level > 79 -%}mdi:battery-charging-80
  {%- elif level > 69 -%}mdi:battery-charging-70
  {%- elif level > 59 -%}mdi:battery-charging-60
  {%- elif level > 49 -%}mdi:battery-charging-50
  {%- elif level > 39 -%}mdi:battery-charging-40
  {%- elif level > 29 -%}mdi:battery-charging-30
  {%- elif level > 19 -%}mdi:battery-charging-20
  {%- elif level > 9 -%}mdi:battery-charging-10
  {%- else -%}mdi:battery-charging-outline
  {%- endif -%}
{%- else -%}
  {%- if level > 99 -%}mdi:battery
  {%- elif level > 89 -%}mdi:battery-90
  {%- elif level > 79 -%}mdi:battery-80
  {%- elif level > 69 -%}mdi:battery-70
  {%- elif level > 59 -%}mdi:battery-60
  {%- elif level > 49 -%}mdi:battery-50
  {%- elif level > 39 -%}mdi:battery-40
  {%- elif level > 29 -%}mdi:battery-30
  {%- elif level > 19 -%}mdi:battery-20
  {%- elif level > 9 -%}mdi:battery-10
  {%- else -%}mdi:battery-outline
  {%- endif -%}
{%- endif %}' but no default was specified
2022-08-03 22:16:25 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set level = states('sensor.landroid_mower_battery') | float -%} {%- if is_state_attr('sensor.landroid_mower_battery', 'charging', 1) -%}
  {%- if level > 99 -%}mdi:battery-charging-100
  {%- elif level > 89 -%}mdi:battery-charging-90
  {%- elif level > 79 -%}mdi:battery-charging-80
  {%- elif level > 69 -%}mdi:battery-charging-70
  {%- elif level > 59 -%}mdi:battery-charging-60
  {%- elif level > 49 -%}mdi:battery-charging-50
  {%- elif level > 39 -%}mdi:battery-charging-40
  {%- elif level > 29 -%}mdi:battery-charging-30
  {%- elif level > 19 -%}mdi:battery-charging-20
  {%- elif level > 9 -%}mdi:battery-charging-10
  {%- else -%}mdi:battery-charging-outline
  {%- endif -%}
{%- else -%}
  {%- if level > 99 -%}mdi:battery
  {%- elif level > 89 -%}mdi:battery-90
  {%- elif level > 79 -%}mdi:battery-80
  {%- elif level > 69 -%}mdi:battery-70
  {%- elif level > 59 -%}mdi:battery-60
  {%- elif level > 49 -%}mdi:battery-50
  {%- elif level > 39 -%}mdi:battery-40
  {%- elif level > 29 -%}mdi:battery-30
  {%- elif level > 19 -%}mdi:battery-20
  {%- elif level > 9 -%}mdi:battery-10
  {%- else -%}mdi:battery-outline
  {%- endif -%}
{%- endif %}' but no default was specified') while processing template 'Template("{% set level = states('sensor.landroid_mower_battery') | float -%} {%- if is_state_attr('sensor.landroid_mower_battery', 'charging', 1) -%}
  {%- if level > 99 -%}mdi:battery-charging-100
  {%- elif level > 89 -%}mdi:battery-charging-90
  {%- elif level > 79 -%}mdi:battery-charging-80
  {%- elif level > 69 -%}mdi:battery-charging-70
  {%- elif level > 59 -%}mdi:battery-charging-60
  {%- elif level > 49 -%}mdi:battery-charging-50
  {%- elif level > 39 -%}mdi:battery-charging-40
  {%- elif level > 29 -%}mdi:battery-charging-30
  {%- elif level > 19 -%}mdi:battery-charging-20
  {%- elif level > 9 -%}mdi:battery-charging-10
  {%- else -%}mdi:battery-charging-outline
  {%- endif -%}
{%- else -%}
  {%- if level > 99 -%}mdi:battery
  {%- elif level > 89 -%}mdi:battery-90
  {%- elif level > 79 -%}mdi:battery-80
  {%- elif level > 69 -%}mdi:battery-70
  {%- elif level > 59 -%}mdi:battery-60
  {%- elif level > 49 -%}mdi:battery-50
  {%- elif level > 39 -%}mdi:battery-40
  {%- elif level > 29 -%}mdi:battery-30
  {%- elif level > 19 -%}mdi:battery-20
  {%- elif level > 9 -%}mdi:battery-10
  {%- else -%}mdi:battery-outline
  {%- endif -%}
{%- endif %}")' for attribute '_attr_icon' in entity 'sensor.landroid_bat'
2022-08-03 22:16:25 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{% set t = state_attr('sensor.landroid_mower_status', 'blade_time') | int %} {% if t != 0 %}
  {{ '%0d d %0.02d h %0.02d min' | format(t // 1440, ((t % 1440) // 60), t % 60) }}
{% endif %}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 421, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1906, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1698, in forgiving_int_filter
    raise_no_default("int", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1395, in raise_no_default
    raise ValueError(
ValueError: Template error: int got invalid input 'None' when rendering template '{% set t = state_attr('sensor.landroid_mower_status', 'blade_time') | int %} {% if t != 0 %}
  {{ '%0d d %0.02d h %0.02d min' | format(t // 1440, ((t % 1440) // 60), t % 60) }}
{% endif %}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 537, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: int got invalid input 'None' when rendering template '{% set t = state_attr('sensor.landroid_mower_status', 'blade_time') | int %} {% if t != 0 %}
  {{ '%0d d %0.02d h %0.02d min' | format(t // 1440, ((t % 1440) // 60), t % 60) }}
{% endif %}' but no default was specified
2022-08-03 22:16:25 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: int got invalid input 'None' when rendering template '{% set t = state_attr('sensor.landroid_mower_status', 'blade_time') | int %} {% if t != 0 %}
  {{ '%0d d %0.02d h %0.02d min' | format(t // 1440, ((t % 1440) // 60), t % 60) }}
{% endif %}' but no default was specified') while processing template 'Template("{% set t = state_attr('sensor.landroid_mower_status', 'blade_time') | int %} {% if t != 0 %}
  {{ '%0d d %0.02d h %0.02d min' | format(t // 1440, ((t % 1440) // 60), t % 60) }}
{% endif %}")' for attribute 'time_formatted' in entity 'sensor.landroid_bladetime'
2022-08-03 22:16:25 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{% set t = state_attr('sensor.landroid_mower_status', 'work_time') | int %} {% if t != 0 %}
  {{ '%0d d %0.02d h %0.02d min' | format(t // 1440, ((t % 1440) // 60), t % 60) }}
{% endif %}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 421, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1906, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1698, in forgiving_int_filter
    raise_no_default("int", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1395, in raise_no_default
    raise ValueError(
ValueError: Template error: int got invalid input 'None' when rendering template '{% set t = state_attr('sensor.landroid_mower_status', 'work_time') | int %} {% if t != 0 %}
  {{ '%0d d %0.02d h %0.02d min' | format(t // 1440, ((t % 1440) // 60), t % 60) }}
{% endif %}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 537, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: int got invalid input 'None' when rendering template '{% set t = state_attr('sensor.landroid_mower_status', 'work_time') | int %} {% if t != 0 %}
  {{ '%0d d %0.02d h %0.02d min' | format(t // 1440, ((t % 1440) // 60), t % 60) }}
{% endif %}' but no default was specified
2022-08-03 22:16:25 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: int got invalid input 'None' when rendering template '{% set t = state_attr('sensor.landroid_mower_status', 'work_time') | int %} {% if t != 0 %}
  {{ '%0d d %0.02d h %0.02d min' | format(t // 1440, ((t % 1440) // 60), t % 60) }}
{% endif %}' but no default was specified') while processing template 'Template("{% set t = state_attr('sensor.landroid_mower_status', 'work_time') | int %} {% if t != 0 %}
  {{ '%0d d %0.02d h %0.02d min' | format(t // 1440, ((t % 1440) // 60), t % 60) }}
{% endif %}")' for attribute 'time_formatted' in entity 'sensor.landroid_totaltime'
2022-08-03 22:16:25 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ (state_attr('sensor.landroid_mower_status', 'distance') | float) / 1000 }}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1679, in forgiving_float_filter
    return float(value)
TypeError: float() argument must be a string or a real number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 421, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1906, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1682, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1395, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'None' when rendering template '{{ (state_attr('sensor.landroid_mower_status', 'distance') | float) / 1000 }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 537, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'None' when rendering template '{{ (state_attr('sensor.landroid_mower_status', 'distance') | float) / 1000 }}' but no default was specified
2022-08-03 22:16:25 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'None' when rendering template '{{ (state_attr('sensor.landroid_mower_status', 'distance') | float) / 1000 }}' but no default was specified') while processing template 'Template("{{ (state_attr('sensor.landroid_mower_status', 'distance') | float) / 1000 }}")' for attribute '_attr_native_value' in entity 'sensor.landroid_dist'
2022-08-03 22:16:25 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ as_timestamp(strptime( state_attr('sensor.landroid_mower_status', 'last_update'), '%H:%M:%S %d/%m/%Y')) | timestamp_custom('%d.%m.%Y %H:%M:%S') }}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1610, in strptime
    return datetime.strptime(string, fmt)
TypeError: strptime() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 421, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1906, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1613, in strptime
    raise_no_default("strptime", string)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1395, in raise_no_default
    raise ValueError(
ValueError: Template error: strptime got invalid input 'None' when rendering template '{{ as_timestamp(strptime( state_attr('sensor.landroid_mower_status', 'last_update'), '%H:%M:%S %d/%m/%Y')) | timestamp_custom('%d.%m.%Y %H:%M:%S') }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 537, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: strptime got invalid input 'None' when rendering template '{{ as_timestamp(strptime( state_attr('sensor.landroid_mower_status', 'last_update'), '%H:%M:%S %d/%m/%Y')) | timestamp_custom('%d.%m.%Y %H:%M:%S') }}' but no default was specified
2022-08-03 22:16:25 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: strptime got invalid input 'None' when rendering template '{{ as_timestamp(strptime( state_attr('sensor.landroid_mower_status', 'last_update'), '%H:%M:%S %d/%m/%Y')) | timestamp_custom('%d.%m.%Y %H:%M:%S') }}' but no default was specified') while processing template 'Template("{{ as_timestamp(strptime( state_attr('sensor.landroid_mower_status', 'last_update'), '%H:%M:%S %d/%m/%Y')) | timestamp_custom('%d.%m.%Y %H:%M:%S') }}")' for attribute '_attr_native_value' in entity 'sensor.landroid_lastupdate'
2022-08-03 22:16:25 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{% set strength = state_attr('sensor.landroid_mower_status', 'rssi') | float -%} {%- if strength > -56 -%}mdi:wifi-strength-4 {% elif strength > -67 -%}mdi:wifi-strength-3 {% elif strength > -78 -%}mdi:wifi-strength-2 {% elif strength > -89 -%}mdi:wifi-strength-1 {%- else -%}mdi:wifi-strength-outline {%- endif %}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1679, in forgiving_float_filter
    return float(value)
TypeError: float() argument must be a string or a real number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 421, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1906, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1682, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1395, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'None' when rendering template '{% set strength = state_attr('sensor.landroid_mower_status', 'rssi') | float -%} {%- if strength > -56 -%}mdi:wifi-strength-4 {% elif strength > -67 -%}mdi:wifi-strength-3 {% elif strength > -78 -%}mdi:wifi-strength-2 {% elif strength > -89 -%}mdi:wifi-strength-1 {%- else -%}mdi:wifi-strength-outline {%- endif %}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 537, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'None' when rendering template '{% set strength = state_attr('sensor.landroid_mower_status', 'rssi') | float -%} {%- if strength > -56 -%}mdi:wifi-strength-4 {% elif strength > -67 -%}mdi:wifi-strength-3 {% elif strength > -78 -%}mdi:wifi-strength-2 {% elif strength > -89 -%}mdi:wifi-strength-1 {%- else -%}mdi:wifi-strength-outline {%- endif %}' but no default was specified
2022-08-03 22:16:25 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'None' when rendering template '{% set strength = state_attr('sensor.landroid_mower_status', 'rssi') | float -%} {%- if strength > -56 -%}mdi:wifi-strength-4 {% elif strength > -67 -%}mdi:wifi-strength-3 {% elif strength > -78 -%}mdi:wifi-strength-2 {% elif strength > -89 -%}mdi:wifi-strength-1 {%- else -%}mdi:wifi-strength-outline {%- endif %}' but no default was specified') while processing template 'Template("{% set strength = state_attr('sensor.landroid_mower_status', 'rssi') | float -%} {%- if strength > -56 -%}mdi:wifi-strength-4 {% elif strength > -67 -%}mdi:wifi-strength-3 {% elif strength > -78 -%}mdi:wifi-strength-2 {% elif strength > -89 -%}mdi:wifi-strength-1 {%- else -%}mdi:wifi-strength-outline {%- endif %}")' for attribute '_attr_icon' in entity 'sensor.landroid_wifi'

**Comment by MTrab** [comment]
Guess you have updated from a very old version.
As seen in the documentation, we no longer provide any sensors, but as preparation for a future mower platform we have moved everything to the vacuum platform.
