### ISSUE TITLE
AttributeError: 'ProductInfo' object has no attribute 'board_id'

### ISSUE THREAD

**Issue by luzik** [MTrab/landroid_cloud#270]
Just updated to latest version, and found something in logs.

I am quite new owner of landroid, but found that entity is unenviable after droid rename in app. Do landroid_cloud supporting renaming ? or I just have to re-add it in app to get it working ?

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 223, in connect
    self._fetch()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 651, in _fetch
    device = DeviceHandler(self._api, product)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 40, in __init__
    self.__mapinfo(api, product)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 89, in __mapinfo
    self.mainboard = ProductInfo(InfoType.BOARD, api, self.chassis.board_id)
AttributeError: 'ProductInfo' object has no attribute 'board_id'
```

**Comment by luzik** [comment]
Yeah, removed also entities. Now I have no entity created, only AttributeError in logs

**Comment by SKis274** [comment]
I got the same error without renaming the mower. I also tried to delete the device and add it again in homeassistent. After restart still the same error. 

HA and landroid_cloud are up2date.

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:208
Integration: Landroid Cloud (documentation, issues)
First occurred: 18:42:23 (3 occurrences)
Last logged: 19:04:23

Error setting up entry configuration.yaml - steffen@*****.com for landroid_cloud
Error setting up entry Worx - steffen@*****.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 223, in connect
    self._fetch()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 651, in _fetch
    device = DeviceHandler(self._api, product)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 40, in __init__
    self.__mapinfo(api, product)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 89, in __mapinfo
    self.mainboard = ProductInfo(InfoType.BOARD, api, self.chassis.board_id)
AttributeError: 'ProductInfo' object has no attribute 'board_id'
```

**Comment by donwolle** [comment]
Same error message here. 


```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:208
Integration: Landroid Cloud (documentation, issues)
First occurred: 19:06:10 (1 occurrences)
Last logged: 19:06:10

Error setting up entry Worx - XXXXXXXXXXXXX@gmail.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 223, in connect
    self._fetch()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 651, in _fetch
    device = DeviceHandler(self._api, product)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 40, in __init__
    self.__mapinfo(api, product)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 89, in __mapinfo
    self.mainboard = ProductInfo(InfoType.BOARD, api, self.chassis.board_id)
AttributeError: 'ProductInfo' object has no attribute 'board_id'
```

**Comment by donwolle** [comment]
I have deleted the integration under "Devices and Services". After that I deleted it in HACS. The folder under "custom_components" was successfully deleted.

After a reboot, I reinstalled Landroid Cloud via HACS, version 2.3.3 and added the integration again under "Devices and Services".  I have checked my access data, that should fit.

Then the error occurs.

**Comment by baccula** [comment]
Getting the same error on HA Supervised 2022.10.2, using latest HACS package. Tried deleting integration and readding, restarted HASS, etc. 

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:208
Integration: Landroid Cloud (documentation, issues)
First occurred: 11:18:33 AM (1 occurrences)
Last logged: 11:18:33 AM

Error setting up entry Worx - baccula@gmail.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 223, in connect
    self._fetch()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 651, in _fetch
    device = DeviceHandler(self._api, product)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 40, in __init__
    self.__mapinfo(api, product)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 89, in __mapinfo
    self.mainboard = ProductInfo(InfoType.BOARD, api, self.chassis.board_id)
AttributeError: 'ProductInfo' object has no attribute 'board_id'
`

**Comment by SKis274** [comment]
I did the same like @donwolle. 

The credentials are fine. Still error.

**Comment by MTrab** [comment]
Really strange.
I run 2 installations and none of them have this error.

**Comment by MTrab** [comment]
Just fired up a fresh install of my dev env, and here I got the error. Will see what's going on.

**Comment by rawrgit** [comment]
I also got this error. Tried uninstall and restart in between without any luck.

**Comment by MTrab** [comment]
CRAP! Yet another API change - they have removed the boards endpoint

**Comment by MTrab** [comment]
Quick fix comming up as soon as checks are passing
