### ISSUE TITLE
v2.3.4 doesn't Work Setup

### ISSUE THREAD

**Issue by sashgithub** [MTrab/landroid_cloud#272]
### Environment:
- Home Assistant version: 2022.6.9
- Landroid_cloud version: 2.3.4
- Operation system: HACS

Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 21:30:11 (3 occurrences)
Last logged: 21:30:41

Unable to install package pyworxcloud==2.1.23: ERROR: Cannot install pyworxcloud because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Logger: aiohttp.server
Source: requirements.py:267
First occurred: 21:30:41 (1 occurrences)
Last logged: 21:30:41

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 146, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 243, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 791, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 362, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 49, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 168, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 183, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 236, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 267, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for landroid_cloud not found: ['pyworxcloud==2.1.23'].

I hope it helps Tor solve the issued.

**Comment by MTrab** [comment]
Try restarting again - perhaps your home assistant haven't picked up on the new pyworxcloud availability yet

**Comment by sashgithub** [comment]
Restart doesn't help.

Same Error log:

Unable to install package pyworxcloud==2.1.23: ERROR: Cannot install pyworxcloud because these package versions have conflicting dependencies. 

:-(

**Comment by MTrab** [comment]
All I can say is that this is a local error in your end. Sorry

**Comment by MTrab** [comment]
As you can see - the version is valid:

https://pypi.org/search/?q=pyworxcloud

**Comment by MTrab** [comment]
Oh! I see you are on a REALLY old Home Assistant version. Please update your Home Assistant.

**Comment by sashgithub** [comment]
I have Version 2022.9.6. It was a writing mistake of me.

I deinstall landroid in HACS and i Install it in HACS again, but the same issue.

**Comment by MTrab** [comment]
Try updating to latest HA - might be some conflicting requirements on earlier versions.
It works on 2022.10

**Comment by sashgithub** [comment]
Upgrade to 2022.10 solve the issued. Thank you for help.
