### ISSUE TITLE
Error during startup of Landroid Integration

### ISSUE THREAD

**Issue by holger-tangermann** [MTrab/landroid_cloud#275]
Reproduce: start or reload the landroid integration in HA

Result: Integration not starting

Error Message: 
<<<
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:208
Integration: Landroid Cloud (documentation, issues)
First occurred: 08:32:05 (3 occurrences)
Last logged: 15:19:09

Error setting up entry configuration.yaml - <username> for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 225, in connect
    self._fetch()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 653, in _fetch
    device = DeviceHandler(self._api, product)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 40, in __init__
    self.__mapinfo(api, product)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 89, in __mapinfo
    self.mainboard = ProductInfo(InfoType.BOARD, api, self.chassis.board_id)
AttributeError: 'ProductInfo' object has no attribute 'board_id'
>>>

**Comment by holger-tangermann** [comment]
error disappeared after last update of landroid integration
