### ISSUE TITLE
setup issue certificate

### ISSUE THREAD

**Issue by J1Buskens** [MTrab/landroid_cloud#279]
Hi
While trying to setup this integration I'm getting the following error:
```
Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:208
Integration: Landroid Cloud ([documentation](https://github.com/MTrab/landroid_cloud/blob/master/README.md), [issues](https://github.com/MTrab/landroid_cloud/issues))
First occurred: 9:54:17 PM (1 occurrences)
Last logged: 9:54:17 PM

Error setting up entry Worx - ***@gmail.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 226, in _call
    req.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.worxlandroid.com/api/v2/users/certificate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 269, in connect
    with self._get_cert() as cert:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 324, in _get_cert
    certresp = self._api.get_cert()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 135, in get_cert
    calldata = self._call("/users/certificate")
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 236, in _call
    raise NotFoundError()
pyworxcloud.exceptions.NotFoundError
```
I am sure that the credential are correct as I tried using them to login to the app and website.

**Comment by MTrab** [comment]
Please create an issue with the required information as stated in the issue template.

Other than that - just tested locally on a fresh Home Assistant without anything else, and found no issues.
