### ISSUE TITLE
integration could not be loaded

### ISSUE THREAD

**Issue by switschel** [MTrab/landroid_cloud#310]
### Describe the issue

Tried out the new pre-release [v3.0.0b1](https://github.com/MTrab/landroid_cloud/releases/tag/v3.0.0b1)
There seems to be some issue with missing dependencies:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 234, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 86, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1076, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_remove
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 760, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/landroid_cloud/__init__.py", line 10, in <module>
    from pyworxcloud import WorxCloud, exceptions
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 10, in <module>
    from .api import LandroidCloudAPI
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 9, in <module>
    from .utils.requests import GET, HEADERS, POST
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/__init__.py", line 9, in <module>
    from .mqtt import MQTT, Command
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/mqtt.py", line 14, in <module>
    from awsiot import mqtt, mqtt_connection_builder
ModuleNotFoundError: No module named 'awsiot'

### What version of Home Assistant Core has the issue?

2023.3.6

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

integration not loaded at all

**Comment by AbsolutK** [comment]
Failed to load here as well

Setup failed for custom integration landroid_cloud: Unable to import component: No module named 'awsiot'

**Comment by erwintenbrink** [comment]
Same here, @MTrab please let me know if i can help u with anything for testing

**Comment by bwarden** [comment]
See https://github.com/MTrab/pyworxcloud/issues/116
Workaround: change `awsiot` to `awsiotsdk` on this line:
https://github.com/MTrab/pyworxcloud/blob/8dd13fd80da2af33e264d1b37e8e0ed579d03227/pyworxcloud/utils/mqtt.py#L14
and use pip to install `awsiotsdk` in your Home Assistant instance.

**Comment by MTrab** [comment]
awsiotsdk just doesn't play nice with HAOS, so need to find another solution :(

**Comment by MTrab** [comment]
A new pre-release has been made available

**Comment by Cosmicbase** [comment]
Hi Malene, after I was a bit overreacted, even mean, I don't want to miss a big thank you to you.

**Comment by riker09** [comment]
> awsiotsdk just doesn't play nice with HAOS, so need to find another solution :(

There was a new release of HAOS (v10.0) recently: https://github.com/home-assistant/operating-system/releases/tag/10.0
Maybe this fixes the issues with `awsiotsdk`?

**Comment by MTrab** [comment]
Awsiotsdk isn't used anymore

**Comment by riker09** [comment]
Then it seems I missed the discussion on switching to that other component (paho?)

Anyway. Thanks for your great work on this. I really appreciate all your efforts and especially your patience. 👍🏻
