### ISSUE TITLE
Error setting up entry Import - erwinknapen@home.nl for landroid_cloud

### ISSUE THREAD

**Issue by toxic049** [MTrab/landroid_cloud#311]
### Describe the issue

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:208
Integration: Landroid Cloud ([documentation](https://github.com/MTrab/landroid_cloud/blob/master/README.md), [issues](https://github.com/MTrab/landroid_cloud/issues))
First occurred: 2:03:34 PM (2 occurrences)
Last logged: 2:11:04 PM
Error setting up entry Import - erwinknapen@home.nl for landroid_cloud

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 226, in _call
    req.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.worxlandroid.com/api/v2/users/certificate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 269, in connect
    with self._get_cert() as cert:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 324, in _get_cert
    certresp = self._api.get_cert()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 135, in get_cert
    calldata = self._call("/users/certificate")
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 236, in _call
    raise NotFoundError()
pyworxcloud.exceptions.NotFoundError

### What version of Home Assistant Core has the issue?

core-2022.12.7

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_landroid_cloud_2023-03-31T12-11-02.412Z.log](https://github.com/MTrab/landroid_cloud/files/11121650/home-assistant_landroid_cloud_2023-03-31T12-11-02.412Z.log)

**Comment by toxic049** [comment]
Ran the update from hacs integrations update interface. Thank you

**Comment by ljmerza** [comment]
im confused. you closed the issue and remove the readme saying this integration was broken? i puylled master and tried and didnt work

**Comment by MTrab** [comment]
Yeah it worked in my test env, but the is an error in the module used

**Comment by MTrab** [comment]
I'll close this and keep it in #282 (which I have just reopened)
