### ISSUE TITLE
Integration not Updating

### ISSUE THREAD

**Issue by cm86** [MTrab/landroid_cloud#319]
### Describe the issue

So here in a new issue.

The Integration works well, but after the update at the start of Home Assistant the integration is not updating the mower.

After every restart of Home Assistant it works.
Unfortunately there are no logs for that.

### What version of Home Assistant Core has the issue?

core-2023.4.4

### What was the last working version of Home Assistant Core?

core-2023.4.4

### What type of installation are you running?

Home Assistant Supervised

### Diagnostics information

nothing right now

**Comment by AlphaZuluNRW** [comment]
Ultimately, only the integration needs to be restarted to get the current values ​​again. After a while, however, it is no longer updated.

**Comment by MTrab** [comment]
Please attach diagnostic info from the device

**Comment by Cosmicbase** [comment]
The same here. When the integration is reloaded, the connect is available again. Added a debug for you. Hope that helps.
[home-assistant_landroid_cloud_2023-04-17T04-40-03.541Z.log](https://github.com/MTrab/landroid_cloud/files/11246289/home-assistant_landroid_cloud_2023-04-17T04-40-03.541Z.log)

**Comment by MTrab** [comment]
More interested in the diagnostics

**Comment by cm86** [comment]
Good morning,
What for diagnostics do you mean?!
From the mower?!

Mit freundlichen Grüßen 
Chris

**Comment by MTrab** [comment]
From the device in Home Assistant.
Integrations - landroid - diagnostics

**Comment by cm86** [comment]
Hello,
I have already activated debug logging.
And restart Home Assistant several times. Actually the integration is also not updating, but I have no point to download some debug logs from the integration…
Screenshot as attachment
![IMG_3768](https://user-images.githubusercontent.com/14919688/232396772-7ea3300e-b214-45c5-901b-746124d0de96.jpeg)

**Comment by roofburner** [comment]
I don't know if this is a "landroid_cloud" problem, or a Worx API problem.

I have the same issue on my Landroid app on my Android.
After a while I get "connection error" in the app when e.g. I toggle the partymode. I think I will open a ticket at Worx/Positec support for this.
Refreshing using the top-down-screen swipe doesn't help.
I need to close/swipe the app away to reinitiate the connection and to get updates in the app.

Same in Home Assistant: reloading the landroid_cloud integration fixes the issue. When I toggle the Partymode in the Android app, I see HTTPS packets comming from a Amazon cloud server (IPv6 changes in time), and my Home Assistant integration get updated. After a while TCP connection with the Amazon cloud server brakes and ends into TIME_WAIT status.

I have TCP keepalive enabled:

```
# cat /proc/sys/net/ipv4/tcp_keepalive_time
7200
# cat /proc/sys/net/ipv4/tcp_keepalive_intvl
75
# cat /proc/sys/net/ipv4/tcp_keepalive_probes
9
```

I will take a tcpdump to analyse it further.

**Comment by MTrab** [comment]
> Hello, I have already activated debug logging. And restart Home Assistant several times. Actually the integration is also not updating, but I have no point to download some debug logs from the integration… Screenshot as attachment ![IMG_3768](https://user-images.githubusercontent.com/14919688/232396772-7ea3300e-b214-45c5-901b-746124d0de96.jpeg)

Click on the device and download diagnostics from left side.

Also, for all of you - when seeing this issue, what happens if you refresh data from the app? Does that introduce new data in Home Assistant?

Does the timestamp in the lower right corner of the app update?

**Comment by MTrab** [comment]
If the robot does not send any data, Home Assistant will also not get data obviously.

**Comment by MTrab** [comment]
Okay - just had the chance to check my running config, and it has lost connection as well.
This seems like a reconnect issue in pyworxcloud as it seems like the API connection has been dropped as no commands are passed to the robot.

**Comment by shaman79** [comment]
I have the same issue on WR153E.

Refreshing the data in app does not refresh data in HA.

This shows in logs:

```
2023-04-16 08:30:46.320 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139998253394784] Cannot request this zone as it is not defined.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/landroid_cloud/services.py", line 143, in async_call_landroid_service
    await api.services[service][ATTR_SERVICE](service_data)
  File "/config/custom_components/landroid_cloud/device_base.py", line 721, in async_set_zone
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 682, in setzone
    raise RequestException("Cannot request this zone as it is not defined.")
pyworxcloud.exceptions.RequestException: Cannot request this zone as it is not defined.
```

**Comment by MTrab** [comment]
> I have the same issue on WR153E.
> 
> Refreshing the data in app does not refresh data in HA.
> 
> This shows in logs:
> 
> ```
> 2023-04-16 08:30:46.320 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139998253394784] Cannot request this zone as it is not defined.
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
>     await hass.services.async_call(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
>     await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
>   File "/config/custom_components/landroid_cloud/services.py", line 143, in async_call_landroid_service
>     await api.services[service][ATTR_SERVICE](service_data)
>   File "/config/custom_components/landroid_cloud/device_base.py", line 721, in async_set_zone
>     await self.hass.async_add_executor_job(
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 682, in setzone
>     raise RequestException("Cannot request this zone as it is not defined.")
> pyworxcloud.exceptions.RequestException: Cannot request this zone as it is not defined.
> ```

That error does not relate to this issue, but rather is one of the missing features in the beta version.

**Comment by roofburner** [comment]
I have opened a ticket (#1564674443) as Positec/Worx. I guess this is what happens: the robot updates the cloud every now and then, but the iOS/Android app loses connection towards the server.
I've seen the status in my smartphone app being up to date, but not on my Home Assistant, or v.v.
I think it may be a design fault at their side?
BTW. Still sniffing on my server to see who sends the first RST on the HTTPS connection.

**Comment by MTrab** [comment]
Close that ticket - it's, as I mentioned, because there is a reconnection issue with pyworxcloud.
I've created an issue in that repo for me to keep track of changes over there: https://github.com/mtrab/pyworxcloud/issues/123

**Comment by roofburner** [comment]
Sorry being so rebellious :-), but I will keep it open :-). I think they should fix my "connection"-error in the Landroid app.
Or will the pyworxcloud-fix fix this issue as well?

Of topic: This is how I can reproduce the Landroid app problem:

Open the app on your smartphone. Be sure you are connected and get updates from the cloud. Don't close it, leave it open and lock your phone.
Wait a long time (like overnight). In the morning, open your app, still being 'active' in the background, and toggle e.g. the party mode => this results in a "connectionerror" message.
This behaviour, I did not experience before their server-move activities.

**Comment by roofburner** [comment]
No bad feelings :-). Both issues smell related to me :-)

**Comment by MTrab** [comment]
[How to download diagnostic data](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics)

**Comment by MTrab** [comment]
Oh - I just saw it is missing. Sorry for that - will be fixed

**Comment by SebastianSiegl** [comment]
Hi, I have no idea if it is somehow connected or another issue. I have the same issue as described here but it also causes my robot not take any command like "start" or "go home". When I refresh the integrations several times sometimes it works then but most of the times the robot is not responding. Is this somehow related to the update issue?

**Comment by MTrab** [comment]
Yes, stupidity from my side, perhaps for those pesky comments in another issue.

Forgot to handle token refreshing, working on it right now

**Comment by SebastianSiegl** [comment]
No worries! Thanks for the update

**Comment by MTrab** [comment]
Yay! And now I managed to get myself banned.
Anyways, don't have time to test much more today, let's see if the ban is lifted by itself

**Comment by moelloman** [comment]
After I installed v3.0.0b3 my HA performance slowed down extremely. I just deactivated it and wait for a new version In the log I see a lot of unsuccessful MQTT requests:
[pyworxcloud.MQTT.Conn_State] Unexpected MQTT disconnect (Connection Refused: unknown reason.) - retrying
(@MTrab no pressure on you. I really appreciate your work).

**Comment by moelloman** [comment]
> Sorry being so rebellious :-), but I will keep it open :-). I think they should fix my "connection"-error in the Landroid app. Or will the pyworxcloud-fix fix this issue as well?
> 
> Of topic: This is how I can reproduce the Landroid app problem:
> 
> Open the app on your smartphone. Be sure you are connected and get updates from the cloud. Don't close it, leave it open and lock your phone. Wait a long time (like overnight). In the morning, open your app, still being 'active' in the background, and toggle e.g. the party mode => this results in a "connectionerror" message. This behaviour, I did not experience before their server-move activities.

I have a similar problem in the app. I can connect but not actively control the mower. Also a refresh doesn't work (connection error). But when the mower send an update it will be show in the app. I updated the FW to 3.28. Also disconnected the mower and added again 2 times. Nothing improved the situation.

**Comment by MTrab** [comment]
Contact Positec about app issues - that I have nothing to do with!

**Comment by MTrab** [comment]
> After I installed v3.0.0b3 my HA performance slowed down extremely. I just deactivated it and wait for a new version In the log I see a lot of unsuccessful MQTT requests: [pyworxcloud.MQTT.Conn_State] Unexpected MQTT disconnect (Connection Refused: unknown reason.) - retrying (@MTrab no pressure on you. I really appreciate your work).

Please revert to b2 - 3 has a serious bug which WILL drag your HA into the gravel and potentially ban you from accessing Positec.
Just got home now and will remove that release ASAP

**Comment by MTrab** [comment]
b4 (fixes this issue) will be up shortly
