### ISSUE TITLE
cannot call the torque sercice, produces traceback in log

### ISSUE THREAD

**Issue by prof7bit** [MTrab/landroid_cloud#336]
### Describe the issue

I have latest homeassistant and latest v3.0.b4 version of this integration.

It is working fine so far, previous connection problems seem gone, but today I wanted to use the **torque** service to change the torque. Homeassistant says something along the lines of  **"error executing service landroid_cloud.torque: unknown error"** and the protocol contains two tracebacks (see below).

### What version of Home Assistant Core has the issue?

core- 2023.4.5

### What version of the Landroid Cloud integration do you have installed

v3.0.b4

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

WR167E 

### Diagnostics information (NOT log entries!)

````
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.4.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.1.24",
    "supervisor": "2023.04.0",
    "host_os": "Home Assistant OS 10.0",
    "docker_version": "23.0.3",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "nodered": {
      "version": "1.2.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "landroid_cloud": {
      "version": "3.0.0b4",
      "requirements": [
        "pyworxcloud==3.1.3"
      ]
    }
  },
  "integration_manifest": {
    "domain": "landroid_cloud",
    "name": "Landroid Cloud",
    "after_dependencies": [
      "http"
    ],
    "codeowners": [
      "@MTrab"
    ],
    "config_flow": true,
    "documentation": "https://github.com/MTrab/landroid_cloud/blob/master/README.md",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/MTrab/landroid_cloud/issues",
    "loggers": [
      "pyworxcloud"
    ],
    "requirements": [
      "pyworxcloud==3.1.3"
    ],
    "version": "3.0.0b4",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "a1c9065f9ab88f849027b63ee90072af",
      "version": 1,
      "domain": "landroid_cloud",
      "title": "**REDACTED**",
      "data": {
        "email": "**REDACTED**",
        "password": "**REDACTED**",
        "type": "Worx"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "cloud": {},
    "device_ids": {
      "Herbert": "097ef334e5f2af9b96933ce42cd1b21a"
    },
    "feature_bits": {},
    "type": "Worx",
    "devices": {
      "Herbert": {
        "_api": {
          "__type": "<class 'pyworxcloud.api.LandroidCloudAPI'>",
          "repr": "<pyworxcloud.api.LandroidCloudAPI object at 0x7f2e8675d030>"
        },
        "_mower": {
          "id": 662428,
          "uuid": "96c53161-131e-4002-9886-7ca4e97b047c",
          "product_id": 69,
          "user_id": 570525,
          "serial_number": "20213026711000327253",
          "mac_address": "34AB95F9006C",
          "name": "Herbert",
          "locked": false,
          "firmware_version": "3.28",
          "firmware_auto_upgrade": true,
          "push_notifications": true,
          "sim": null,
          "push_notifications_level": "warning",
          "test": false,
          "iot_registered": true,
          "mqtt_registered": true,
          "pin_code": null,
          "registered_at": "2022-05-14 00:00:00",
          "online": true,
          "app_settings": null,
          "protocol": 0,
          "pending_radio_link_validation": null,
          "capabilities": [
            "auto_lock",
            "bluetooth_control",
            "bluetooth_pairing",
            "digital_fence_settings",
            "lock",
            "mqtt",
            "multi_zone",
            "multi_zone_percentage",
            "one_time_scheduler",
            "pairing_smartconfig",
            "pause_over_wire",
            "rain_delay",
            "rain_delay_start",
            "safe_go_home",
            "scheduler_two_slots",
            "unrestricted_mowing_time"
          ],
          "capabilities_available": [],
          "features": {
            "auto_lock": 3.25,
            "bluetooth_control": 3.2,
            "bluetooth_pairing": true,
            "chassis": "m_2021",
            "digital_fence_settings": 3.25,
            "display_type": "lcd",
            "input_type": "keyboard_push_knob",
            "lock": true,
            "mqtt": true,
            "multi_zone": true,
            "multi_zone_percentage": true,
            "multi_zone_zones": 4,
            "one_time_scheduler": 3.15,
            "pause_over_wire": 3.26,
            "rain_delay": true,
            "rain_delay_start": 3.08,
            "safe_go_home": 3.25,
            "scheduler_two_slots": 3.15,
            "unrestricted_mowing_time": true,
            "wifi_pairing": "smartconfig"
          },
          "accessories": null,
          "mqtt_endpoint": "iot.eu-west-1.worxlandroid.com",
          "mqtt_topics": {
            "command_in": "PRM100/34AB95F9006C/commandIn",
            "command_out": "PRM100/34AB95F9006C/commandOut"
          },
          "warranty_registered": true,
          "purchased_at": "2022-05-14 00:00:00",
          "warranty_expires_at": "2025-05-14 00:00:00",
          "setup_location": {
            "latitude": xxxxxx,
            "longitude": xxxxxx
          },
          "city": {
            "id": xxxxxx,
            "country_id": 276,
            "name": "xxxxxxxx",
            "latitude": xxxxxxxx,
            "longitude": xxxxxx,
            "created_at": "2018-02-15T22:13:30+01:00",
            "updated_at": "2018-02-15T22:13:30+01:00"
          },
          "time_zone": "Europe/Berlin",
          "lawn_size": 330,
          "lawn_perimeter": 151,
          "auto_schedule_settings": {
            "boost": 0,
            "exclusion_scheduler": {
              "days": [
                {
                  "slots": [],
                  "exclude_day": false
                },
                {
                  "slots": [],
                  "exclude_day": false
                },
                {
                  "slots": [],
                  "exclude_day": false
                },
                {
                  "slots": [],
                  "exclude_day": false
                },
                {
                  "slots": [],
                  "exclude_day": false
                },
                {
                  "slots": [],
                  "exclude_day": false
                },
                {
                  "slots": [],
                  "exclude_day": false
                }
              ],
              "exclude_nights": true
            },
            "grass_type": null,
            "irrigation": null,
            "nutrition": null,
            "soil_type": null
          },
          "auto_schedule": false,
          "improvement": false,
          "diagnostic": false,
          "distance_covered": 478141,
          "mower_work_time": 30836,
          "blade_work_time": 30288,
          "blade_work_time_reset": 29923,
          "blade_work_time_reset_at": "2023-04-16 16:57:00",
          "battery_charge_cycles": 192,
          "battery_charge_cycles_reset": 0,
          "battery_charge_cycles_reset_at": null,
          "created_at": "2021-12-08 01:06:24",
          "updated_at": "2022-10-30 01:20:52",
          "last_status": {
            "timestamp": "2023-04-19T05:20:53+02:00",
            "payload": {
              "cfg": {
                "id": 0,
                "sn": "20213026711000327253",
                "dt": "19/04/2023",
                "tm": "07:20:56",
                "lg": "de",
                "cmd": 0,
                "sc": {
                  "m": 1,
                  "d": [
                    [
                      "00:00",
                      0,
                      0
                    ],
                    [
                      "07:00",
                      45,
                      0
                    ],
                    [
                      "07:00",
                      45,
                      0
                    ],
                    [
                      "07:00",
                      45,
                      0
                    ],
                    [
                      "07:00",
                      45,
                      0
                    ],
                    [
                      "07:00",
                      45,
                      0
                    ],
                    [
                      "09:00",
                      120,
                      1
                    ]
                  ],
                  "dd": [
                    [
                      "00:00",
                      0,
                      0
                    ],
                    [
                      "17:00",
                      120,
                      0
                    ],
                    [
                      "17:00",
                      120,
                      0
                    ],
                    [
                      "17:00",
                      120,
                      0
                    ],
                    [
                      "17:00",
                      120,
                      0
                    ],
                    [
                      "17:00",
                      120,
                      0
                    ],
                    [
                      "15:00",
                      120,
                      0
                    ]
                  ],
                  "distm": 0,
                  "p": 50,
                  "ots": {
                    "wtm": 90,
                    "bc": 0
                  }
                },
                "mz": [
                  0,
                  0,
                  0,
                  0
                ],
                "mzv": [
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0
                ],
                "rd": 0,
                "al": {
                  "lvl": 0,
                  "t": 60
                },
                "tq": -20
              },
              "dat": {
                "mac": "34AB95F9006C",
                "fw": 3.2800000000000002,
                "fwb": 1,
                "ls": 7,
                "le": 0,
                "conn": "wifi",
                "bt": {
                  "t": 7.2,
                  "v": 19.07,
                  "p": 99,
                  "nr": 192,
                  "c": 0,
                  "m": 1
                },
                "dmp": [
                  -2.2,
                  -0.2,
                  137.1
                ],
                "st": {
                  "b": 30308,
                  "d": 478489,
                  "wt": 30856,
                  "bl": 151
                },
                "act": 1,
                "rsi": -60,
                "lk": 0,
                "tr": 0,
                "lz": 0,
                "rain": {
                  "s": 0,
                  "cnt": 0
                }
              }
            }
          }
        },
        "_tz": null,
        "id": 662428,
        "uuid": "96c53161-131e-4002-9886-7ca4e97b047c",
        "product_id": 69,
        "serial_number": "20213026711000327253",
        "mac_address": "34AB95F9006C",
        "name": "Herbert",
        "locked": false,
        "sim": null,
        "mqtt_registered": true,
        "pin_code": null,
        "registered_at": "2022-05-14T00:00:00+02:00",
        "online": true,
        "protocol": 0,
        "capabilities": {
          "__type": "<class 'pyworxcloud.utils.capability.Capability'>",
          "repr": "<pyworxcloud.utils.capability.Capability object at 0x7f2e85fddbd0>"
        },
        "capabilities_available": [],
        "accessories": null,
        "setup_location": {
          "latitude": 52.46185054406501,
          "longitude": 9.553602437860398
        },
        "city": {
          "id": 2856022,
          "country_id": 276,
          "name": "Otternhagen",
          "latitude": 52.513821,
          "longitude": 9.52635,
          "created_at": "2018-02-15T22:13:30+01:00",
          "updated_at": "2018-02-15T22:13:30+01:00"
        },
        "time_zone": "Europe/Berlin",
        "improvement": false,
        "diagnostic": false,
        "mower_work_time": 30836,
        "last_status": {
          "timestamp": "2023-04-19T05:20:53+02:00",
          "payload": {
            "cfg": {
              "id": 0,
              "sn": "20213026711000327253",
              "dt": "19/04/2023",
              "tm": "07:20:56",
              "lg": "de",
              "cmd": 0,
              "sc": {
                "m": 1,
                "d": [
                  [
                    "00:00",
                    0,
                    0
                  ],
                  [
                    "07:00",
                    45,
                    0
                  ],
                  [
                    "07:00",
                    45,
                    0
                  ],
                  [
                    "07:00",
                    45,
                    0
                  ],
                  [
                    "07:00",
                    45,
                    0
                  ],
                  [
                    "07:00",
                    45,
                    0
                  ],
                  [
                    "09:00",
                    120,
                    1
                  ]
                ],
                "dd": [
                  [
                    "00:00",
                    0,
                    0
                  ],
                  [
                    "17:00",
                    120,
                    0
                  ],
                  [
                    "17:00",
                    120,
                    0
                  ],
                  [
                    "17:00",
                    120,
                    0
                  ],
                  [
                    "17:00",
                    120,
                    0
                  ],
                  [
                    "17:00",
                    120,
                    0
                  ],
                  [
                    "15:00",
                    120,
                    0
                  ]
                ],
                "distm": 0,
                "p": 50,
                "ots": {
                  "wtm": 90,
                  "bc": 0
                }
              },
              "mz": [
                0,
                0,
                0,
                0
              ],
              "mzv": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
              ],
              "rd": 0,
              "al": {
                "lvl": 0,
                "t": 60
              },
              "tq": -20
            },
            "dat": {
              "mac": "34AB95F9006C",
              "fw": 3.2800000000000002,
              "fwb": 1,
              "ls": 7,
              "le": 0,
              "conn": "wifi",
              "bt": {
                "t": 7.2,
                "v": 19.07,
                "p": 99,
                "nr": 192,
                "c": 0,
                "m": 1
              },
              "dmp": [
                -2.2,
                -0.2,
                137.1
              ],
              "st": {
                "b": 30308,
                "d": 478489,
                "wt": 30856,
                "bl": 151
              },
              "act": 1,
              "rsi": -60,
              "lk": 0,
              "tr": 0,
              "lz": 0,
              "rain": {
                "s": 0,
                "cnt": 0
              }
            }
          }
        },
        "battery": {
          "cycles": {
            "total": 193,
            "current": 0,
            "reset_at": null,
            "reset_time": null
          },
          "temperature": 11.8,
          "voltage": 19.55,
          "percent": 100,
          "charging": false
        },
        "blades": {
          "total_on": 30361,
          "reset_at": 29923,
          "reset_time": "2023-04-16T16:57:00+02:00",
          "current_on": 438
        },
        "chassis": {},
        "error": {
          "id": 0,
          "description": "no error"
        },
        "orientation": {
          "pitch": -1.7,
          "roll": -2.6,
          "yaw": 136.1
        },
        "rainsensor": {
          "delay": 0,
          "triggered": false,
          "remaining": 0
        },
        "status": {
          "id": 1,
          "description": "home"
        },
        "zone": {
          "current": 0,
          "index": 0,
          "indicies": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "starting_point": [
            0,
            0,
            0,
            0
          ]
        },
        "warranty": {
          "expires_at": "2025-05-14T00:00:00+02:00",
          "registered": true,
          "expired": false
        },
        "firmware": {
          "auto_upgrade": true,
          "version": "3.28"
        },
        "schedules": {
          "next_schedule_start": "2023-04-19T17:00:00+02:00",
          "time_extension": 50,
          "active": true,
          "auto_schedule": {
            "settings": {
              "boost": 0,
              "exclusion_scheduler": {
                "days": [
                  {
                    "slots": [],
                    "exclude_day": false
                  },
                  {
                    "slots": [],
                    "exclude_day": false
                  },
                  {
                    "slots": [],
                    "exclude_day": false
                  },
                  {
                    "slots": [],
                    "exclude_day": false
                  },
                  {
                    "slots": [],
                    "exclude_day": false
                  },
                  {
                    "slots": [],
                    "exclude_day": false
                  },
                  {
                    "slots": [],
                    "exclude_day": false
                  }
                ],
                "exclude_nights": true
              },
              "grass_type": null,
              "irrigation": null,
              "nutrition": null,
              "soil_type": null
            },
            "enabled": false
          },
          "primary": {
            "monday": {
              "start": "07:00",
              "end": "08:07",
              "duration": 45,
              "boundary": false
            },
            "tuesday": {
              "start": "07:00",
              "end": "08:07",
              "duration": 45,
              "boundary": false
            },
            "wednesday": {
              "start": "07:00",
              "end": "08:07",
              "duration": 45,
              "boundary": false
            },
            "thursday": {
              "start": "07:00",
              "end": "08:07",
              "duration": 45,
              "boundary": false
            },
            "friday": {
              "start": "07:00",
              "end": "08:07",
              "duration": 45,
              "boundary": false
            },
            "saturday": {
              "start": "09:00",
              "end": "12:00",
              "duration": 120,
              "boundary": true
            },
            "sunday": {
              "start": "00:00",
              "end": "00:00",
              "duration": 0,
              "boundary": false
            }
          },
          "secondary": {
            "monday": {
              "start": "17:00",
              "end": "20:00",
              "duration": 120,
              "boundary": false
            },
            "tuesday": {
              "start": "17:00",
              "end": "20:00",
              "duration": 120,
              "boundary": false
            },
            "wednesday": {
              "start": "17:00",
              "end": "20:00",
              "duration": 120,
              "boundary": false
            },
            "thursday": {
              "start": "17:00",
              "end": "20:00",
              "duration": 120,
              "boundary": false
            },
            "friday": {
              "start": "17:00",
              "end": "20:00",
              "duration": 120,
              "boundary": false
            },
            "saturday": {
              "start": "15:00",
              "end": "18:00",
              "duration": 120,
              "boundary": false
            },
            "sunday": {
              "start": "00:00",
              "end": "00:00",
              "duration": 0,
              "boundary": false
            }
          }
        },
        "in_topic": "PRM100/34AB95F9006C/commandIn",
        "out_topic": "PRM100/34AB95F9006C/commandOut",
        "model": "Model info not available in API",
        "_DeviceHandler__is_decoded": true,
        "_DeviceHandler__raw_data": "{\"cfg\":{\"id\":62457,\"lg\":\"de\",\"tm\":\"14:17:59\",\"dt\":\"19/04/2023\",\"sc\":{\"m\":1,\"distm\":0,\"ots\":{\"bc\":0,\"wtm\":90},\"p\":50,\"d\":[[\"00:00\",0,0],[\"07:00\",45,0],[\"07:00\",45,0],[\"07:00\",45,0],[\"07:00\",45,0],[\"07:00\",45,0],[\"09:00\",120,1]],\"dd\":[[\"00:00\",0,0],[\"17:00\",120,0],[\"17:00\",120,0],[\"17:00\",120,0],[\"17:00\",120,0],[\"17:00\",120,0],[\"15:00\",120,0]]},\"cmd\":0,\"mz\":[0,0,0,0],\"mzv\":[0,0,0,0,0,0,0,0,0,0],\"rd\":0,\"sn\":\"20213026711000327253\",\"al\":{\"lvl\":0,\"t\":60},\"tq\":-20},\"dat\":{\"mac\":\"34AB95F9006C\",\"fw\":3.28,\"fwb\":1,\"bt\":{\"t\":11.8,\"v\":19.55,\"p\":100,\"nr\":193,\"c\":0,\"m\":0},\"dmp\":[-1.7,-2.6,136.1],\"st\":{\"b\":30361,\"d\":479372,\"wt\":30909,\"bl\":151},\"ls\":1,\"le\":0,\"lz\":0,\"rsi\":-52,\"lk\":0,\"act\":1,\"tr\":0,\"conn\":\"wifi\",\"rain\":{\"s\":0,\"cnt\":0},\"time\":{\"r\":0,\"l\":0}}}",
        "_DeviceHandler__json_data": {
          "cfg": {
            "id": 62457,
            "lg": "de",
            "tm": "14:17:59",
            "dt": "19/04/2023",
            "sc": {
              "m": 1,
              "distm": 0,
              "ots": {
                "bc": 0,
                "wtm": 90
              },
              "p": 50,
              "d": [
                [
                  "00:00",
                  0,
                  0
                ],
                [
                  "07:00",
                  45,
                  0
                ],
                [
                  "07:00",
                  45,
                  0
                ],
                [
                  "07:00",
                  45,
                  0
                ],
                [
                  "07:00",
                  45,
                  0
                ],
                [
                  "07:00",
                  45,
                  0
                ],
                [
                  "09:00",
                  120,
                  1
                ]
              ],
              "dd": [
                [
                  "00:00",
                  0,
                  0
                ],
                [
                  "17:00",
                  120,
                  0
                ],
                [
                  "17:00",
                  120,
                  0
                ],
                [
                  "17:00",
                  120,
                  0
                ],
                [
                  "17:00",
                  120,
                  0
                ],
                [
                  "17:00",
                  120,
                  0
                ],
                [
                  "15:00",
                  120,
                  0
                ]
              ]
            },
            "cmd": 0,
            "mz": [
              0,
              0,
              0,
              0
            ],
            "mzv": [
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0
            ],
            "rd": 0,
            "sn": "20213026711000327253",
            "al": {
              "lvl": 0,
              "t": 60
            },
            "tq": -20
          },
          "dat": {
            "mac": "34AB95F9006C",
            "fw": 3.28,
            "fwb": 1,
            "bt": {
              "t": 11.8,
              "v": 19.55,
              "p": 100,
              "nr": 193,
              "c": 0,
              "m": 0
            },
            "dmp": [
              -1.7,
              -2.6,
              136.1
            ],
            "st": {
              "b": 30361,
              "d": 479372,
              "wt": 30909,
              "bl": 151
            },
            "ls": 1,
            "le": 0,
            "lz": 0,
            "rsi": -52,
            "lk": 0,
            "act": 1,
            "tr": 0,
            "conn": "wifi",
            "rain": {
              "s": 0,
              "cnt": 0
            },
            "time": {
              "r": 0,
              "l": 0
            }
          }
        },
        "rssi": -52,
        "statistics": {
          "worktime_blades_on": 30361,
          "distance": 479372,
          "worktime_total": 30909
        },
        "updated": "2023-04-19T14:17:59+02:00",
        "torque": -20,
        "partymode_enabled": false
      }
    }
  }
}
````

### Relevant log entries

```txt
2023-04-19 14:21:49.842 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2023-04-19 14:21:49.843 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'DeviceHandler' object has no attribute 'send'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/landroid_cloud/services.py", line 143, in async_call_landroid_service
    await api.services[service][ATTR_SERVICE](service_data)
  File "/config/custom_components/landroid_cloud/devices/worx.py", line 162, in async_set_torque
    partial(device.send, json.dumps(tmpdata))
AttributeError: 'DeviceHandler' object has no attribute 'send'
2023-04-19 14:21:49.848 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139837681868208] Error handling message: Unknown error (unknown_error) Bernd from 2001:9e8:6be9:5300:80d1:4bff:fe77:7cfd (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 647, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1533, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 410, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 454, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 477, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/landroid_cloud/services.py", line 143, in async_call_landroid_service
    await api.services[service][ATTR_SERVICE](service_data)
  File "/config/custom_components/landroid_cloud/devices/worx.py", line 162, in async_set_torque
    partial(device.send, json.dumps(tmpdata))
AttributeError: 'DeviceHandler' object has no attribute 'send'
```

**Comment by MTrab** [comment]
Yeah - you've found one of the functions that isn't functional in the beta version
