### ISSUE TITLE
Mower stopped updating

### ISSUE THREAD

**Issue by spockster1985** [MTrab/landroid_cloud#341]
### Describe the issue

Mower stopped updating after error in the log file.

### What version of Home Assistant Core has the issue?

core-2023.3.6

### What version of the Landroid Cloud integration do you have installed

v3.0.0b4

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

Worx WR105SI

### Diagnostics information (NOT log entries!)

-

### Relevant log entries

```txt
2023-04-20 03:30:56.955 ERROR (Thread-4 (_thread_main)) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/requests.py", line 42, in POST
    req.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://id.eu.worx.com/oauth/token
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1558, in loop_read
    return self._loop_rc_handle(rc)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2350, in _loop_rc_handle
    self._do_on_disconnect(rc, properties)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3475, in _do_on_disconnect
    on_disconnect(self, self._userdata, rc)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/mqtt.py", line 198, in _on_disconnect
    self._api.update_token()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 71, in update_token
    resp = POST(url, request_body, HEADERS())
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/requests.py", line 60, in POST
    raise APIError(err)
pyworxcloud.exceptions.APIError: 504 Server Error: Gateway Time-out for url: https://id.eu.worx.com/oauth/token
```

**Comment by MTrab** [comment]
Moved to the pyworxcloud thread
