### ISSUE TITLE
Integration Fails for 1.5+

### ISSUE THREAD

**Issue by jamiewalters** [MTrab/landroid_cloud#35]
I can integrate the component up to 1.4.1 after that it fails with the following:
```
2020-05-14 12:44:11 INFO (MainThread) [homeassistant.setup] Setting up landroid_cloud
2020-05-14 12:44:12 DEBUG (MainThread) [custom_components.landroid_cloud] Connecting to device ID 0 (********@****.***)
2020-05-14 12:44:14 DEBUG (MainThread) [custom_components.landroid_cloud] Forcing update for ****
2020-05-14 12:44:15 ERROR (MainThread) [homeassistant.setup] Error during setup of component landroid_cloud
  File "/config/custom_components/landroid_cloud/__init__.py", line 119, in async_setup
  File "/config/custom_components/landroid_cloud/__init__.py", line 242, in async_force_update
 - [landroid_cloud](https://www.home-assistant.io/integrations/landroid_cloud/)
 - [landroid_cloud](https://www.home-assistant.io/integrations/landroid_cloud/)
 - [landroid_cloud](https://www.home-assistant.io/integrations/landroid_cloud/)
 - [landroid_cloud](https://www.home-assistant.io/integrations/landroid_cloud/)
 - [landroid_cloud](https://www.home-assistant.io/integrations/landroid_cloud/)
2020-05-14 12:45:02 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event platform_discovered[L]: service=load_platform.sensor, platform=landroid_cloud, discovered=[{'name': 'landroid_*****', 'friendly': '*****', 'id': 0}]>
2020-05-14 12:45:02 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform landroid_cloud.sensor: Unable to set up component.
 - [landroid_cloud](https://www.home-assistant.io/integrations/landroid_cloud/)
 - landroid_cloud.sensor
 - [landroid_cloud](https://www.home-assistant.io/integrations/landroid_cloud/)
 - [landroid_cloud](https://www.home-assistant.io/integrations/landroid_cloud/)
 - landroid_cloud.sensor
2020-05-14 12:45:25 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event hacs/repository[L]: id=1337, action=registration, repository=MTrab/landroid_cloud, repository_id=None>
 - [landroid_cloud](https://www.home-assistant.io/integrations/landroid_cloud/)
 - landroid_cloud.sensor
 - [landroid_cloud](https://www.home-assistant.io/integrations/landroid_cloud/)
 - landroid_cloud.sensor

```

**Comment by MTrab** [comment]
Could you please format the error message correct?

Almost everyone runs 1.5+ and have no issues.

**Comment by jamiewalters** [comment]
Formatted. I can run up to 1.4.1, after that it fails with that error.

**Comment by MTrab** [comment]
Strange - could you try reinstalling the component and doublecheck the config syntax.

**Comment by jamiewalters** [comment]
tried that a few times, is it the same syntax for 1.4, I downgrade to 1.4 and it runs with the same config ...

```
landroid_cloud:
  - email: "****@***.com"
    password: "password"
```

**Comment by MTrab** [comment]
Unfortunately this is not an error I have seen before, and I have no idea why it's not working for you.

Do you have the possibility to setup a clean Home Assistant and install the component on that?

**Comment by MTrab** [comment]
Did you manage to fix this?

**Comment by irqnet** [comment]
I also got a problem setting up the component on v1.6.1

`
Logger: homeassistant.setup
Source: custom_components/landroid_cloud/__init__.py:247
First occurred: 07:49:30 (1 occurrences)
Last logged: 07:49:30

Error during setup of component landroid_cloud

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/landroid_cloud/__init__.py", line 124, in async_setup
    await api.async_force_update()
  File "/config/custom_components/landroid_cloud/__init__.py", line 247, in async_force_update
    await self._hass.async_add_executor_job(self._client.getStatus)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyworxcloud/__init__.py", line 152, in getStatus
    self._decodeData(status)
  File "/usr/local/lib/python3.7/site-packages/pyworxcloud/__init__.py", line 158, in _decodeData
    self.rssi = data['dat']['rsi']
KeyError: 'dat'`



![grafik](https://user-images.githubusercontent.com/32534199/82868921-b5c2ab00-9f2d-11ea-9741-970620f66a25.png)

**Comment by MTrab** [comment]
@irqnet - not same error. Yours seems to connect, but no data is returned.

**Comment by irqnet** [comment]
> @irqnet - not same error. Yours seems to connect, but no data is returned.

You're right. I've restarted the landroid mower and it's working again. Seems to be a communication problem with my wifi.

**Comment by jamiewalters** [comment]
It works now, I did a clean install of 0.110 tried the plugin a short while ago, works fine now.
