### ISSUE TITLE
Error setting up entry Import for landroid_cloud

### ISSUE THREAD

**Issue by mdzhigarov** [MTrab/landroid_cloud#356]
### Describe the issue

I installed Landroid Cloud master using HACS. 
Then I set up the credentials inside the configuration.yaml as described in https://github.com/mtrab/landroid_cloud:
```
landroid_cloud:
  - email: this@example.com
    password: YourPassword
```

During HASSIO startup I'm getting the error "Error setting up entry Import - m.dzhigarov@gmail.com for landroid_cloud". No entries show up in the integration.

Please advise

### What version of Home Assistant Core has the issue?

2023.4.2

### What version of the Landroid Cloud integration do you have installed

master

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

wr141e

### Diagnostics information (NOT log entries!)

.

### Relevant log entries

```txt
Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:208
Integration: Landroid Cloud (documentation, issues)
First occurred: 9:48:33 AM (1 occurrences)
Last logged: 9:48:33 AM

Error setting up entry Import - m.dzhigarov@gmail.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 226, in _call
    req.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.worxlandroid.com/api/v2/users/certificate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 269, in connect
    with self._get_cert() as cert:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 324, in _get_cert
    certresp = self._api.get_cert()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 135, in get_cert
    calldata = self._call("/users/certificate")
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 236, in _call
    raise NotFoundError()
pyworxcloud.exceptions.NotFoundError
```

**Comment by mdzhigarov** [comment]
Resolved by updating to latest beta version
