### ISSUE TITLE
Certificate URL error

### ISSUE THREAD

**Issue by Jeetah** [MTrab/landroid_cloud#358]
### Describe the issue

Currently it is not possible for me to setup the integration - user & password are ok. This appears in the logs:

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.worxlandroid.com/api/v2/users/certificate

### What version of Home Assistant Core has the issue?

2023.4.6

### What version of the Landroid Cloud integration do you have installed

latest official

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

M500

### Diagnostics information (NOT log entries!)

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:208
Integration: Landroid Cloud ([documentation](https://github.com/MTrab/landroid_cloud/blob/master/README.md), [issues](https://github.com/MTrab/landroid_cloud/issues))
First occurred: 10:52:41 (4 occurrences)
Last logged: 10:58:55
Error setting up entry Worx - villagehero@gmx.de for landroid_cloud

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 226, in _call
    req.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.worxlandroid.com/api/v2/users/certificate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 269, in connect
    with self._get_cert() as cert:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 324, in _get_cert
    certresp = self._api.get_cert()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 135, in get_cert
    calldata = self._call("/users/certificate")
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 236, in _call
    raise NotFoundError()
pyworxcloud.exceptions.NotFoundError

### Relevant log entries

```txt
Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:208
Integration: Landroid Cloud (documentation, issues)
First occurred: 10:52:41 (4 occurrences)
Last logged: 10:58:55
Error setting up entry Worx - villagehero@gmx.de for landroid_cloud

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 226, in _call
    req.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.worxlandroid.com/api/v2/users/certificate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 269, in connect
    with self._get_cert() as cert:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 324, in _get_cert
    certresp = self._api.get_cert()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 135, in get_cert
    calldata = self._call("/users/certificate")
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 236, in _call
    raise NotFoundError()
pyworxcloud.exceptions.NotFoundError
```

**Comment by MTrab** [comment]
Please update to latest beta
