### ISSUE TITLE
Set-up not possible

### ISSUE THREAD

**Issue by docb7** [MTrab/landroid_cloud#359]
### Describe the issue

Hi,
it is the first time I wanted to install / set up the landroid cloud, but unfortunately it is not possible. I (hope I) followed the install instructions, but when after entering my email and password, I get the error with installation:

2023-04-28 22:10:01.520 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - xx@xxxx.com for landroid_cloud
File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup

Hope the provided info helps.
Best regards
Ben

### What version of Home Assistant Core has the issue?

core-2023.4.6

### What version of the Landroid Cloud integration do you have installed

2.3.4

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

WR130E

### Diagnostics information (NOT log entries!)

Not possible because it happens before I am able to activate the debug log

### Relevant log entries

```txt
2023-04-28 22:20:28.544 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - xx@xx.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 226, in _call
    req.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.worxlandroid.com/api/v2/users/certificate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 269, in connect
    with self._get_cert() as cert:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 324, in _get_cert
    certresp = self._api.get_cert()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 135, in get_cert
    calldata = self._call("/users/certificate")
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 236, in _call
    raise NotFoundError()
pyworxcloud.exceptions.NotFoundError
```

**Comment by MTrab** [comment]
As mentioned on the frontpage. You need to use latest beta

**Comment by docb7** [comment]
Thank you very much and for all other blind beginners as me - if you install Landroid Cloud via HACS - there is a switch "show beta versions" which you need to activate ;-)
