### ISSUE TITLE
Not initialising for me

### ISSUE THREAD

**Issue by nigels0** [MTrab/landroid_cloud#371]
### Describe the issue

I’ve tried to activate this, but I’m getting no luck. Log entry attached. Can’t see a beta version to try instead. 

Your help would be most appreciated!

### What version of Home Assistant Core has the issue?

2023.4.6

### What version of the Landroid Cloud integration do you have installed

Latest

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid WR141E

### Diagnostics information (NOT log entries!)

Not here

### Relevant log entries

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 269, in connect
    with self._get_cert() as cert:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 324, in _get_cert
    certresp = self._api.get_cert()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 135, in get_cert
    calldata = self._call("/users/certificate")
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 236, in _call
    raise NotFoundError()
pyworxcloud.exceptions.NotFoundError
```

**Comment by jack171907** [comment]
anche io ho lo stesso problema , configurazione non riuscita

non trovo la beta

**Comment by MTrab** [comment]
Please write English!

**Comment by MTrab** [comment]
Also, this issue is resolved in the beta versions.
Please go to HACS select redownload and enable beta versions
