### ISSUE TITLE
Uncaught thread exception

### ISSUE THREAD

**Issue by GSzabados** [MTrab/landroid_cloud#381]
### Describe the issue

The mower does not react to commands, neither updates any data. The exception seems to happen at HA start.

### What version of Home Assistant Core has the issue?

core-2023.4.5

### What version of the Landroid Cloud integration do you have installed

3.0.1

### What type of installation are you running?

Home Assistant Supervised

### Which make and model is the mower used for this integration?

Worx Landroid M500

### Diagnostics information (NOT log entries!)

None

### Relevant log entries

```txt
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:391
First occurred: 24 May 2023 at 04:09:38 (1 occurrences)
Last logged: 24 May 2023 at 04:09:38

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/mqtt.py", line 148, in _forward_on_message
    self._on_update(msg)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 305, in _on_update
    self._decode_data(device)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 364, in _decode_data
    data["dat"]["modules"]["4G"]["gps"]["coo"][0],
KeyError: 'gps'
```

### Additional information

I am submitting this report from a phone. I will add diagnostic information once I get to a computer.

**Comment by MTrab** [comment]
Strange error, as there's already a check if that key exists.
Will be avaiting the diagnostics before looking more into this.

**Comment by GSzabados** [comment]
@MTrab, I generated the diagnostic information, but I am not really happy to share publicly, as it still contains City name, geo coo coordinates, uuid, serial number, mac address, ICCID, IMSI, etc...

**Comment by MTrab** [comment]
As long as you DO NOT touch ANYTHING regarding the Modules/GPS section as I need that specific part

**Comment by GSzabados** [comment]
@MTrab, I emailed the diagnostic log to you.

**Comment by MTrab** [comment]
The diagnostics checks out - shouldn't generate this error.
No idea where why this happens.
Could you share the credentials for the account?

**Comment by GSzabados** [comment]
The payload's geo, section of the log contains a coo section which is the actual location of the mower. It is automatically redacted at other places, but not there and neither in the raw_data.

**Comment by GSzabados** [comment]
> Strange error, as there's already a check if that key exists.

By any chance have you just added that check recently? I mean between 3.0.0b6 and 3.0.1?

I reloaded the integration, no error, restarted HA, no error. It might be was caught as the integration was updating at the previous start of HA. (I am not sure that did I update to 3.0.1 just before, or one HA restart earlier.)

But currently I cannot reproduce the error.

**Comment by MTrab** [comment]
No, that check has been there for ages - that part hasn't changed since the version 2 range

**Comment by MTrab** [comment]
I'll close this for now

**Comment by GSzabados** [comment]
Ok, no worries. I thought the same. If it pops up again, I will ask you to reopen then.

Thanks for looking at it!

**Comment by GSzabados** [comment]
Actually, I just looked at the logs, and I do see the same error message from the morning:

Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:391
First occurred: 03:55:44 (1 occurrences)
Last logged: 03:55:44

```
Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/mqtt.py", line 148, in _forward_on_message
    self._on_update(msg)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 305, in _on_update
    self._decode_data(device)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 364, in _decode_data
    data["dat"]["modules"]["4G"]["gps"]["coo"][0],
KeyError: 'gps'

```

**Comment by GSzabados** [comment]
And of course, since that there is no update on the mower anymore.

**Comment by MTrab** [comment]
I think I'd need your credentials to test this any further - I don't have any devices with GPS capabilities.

Credentials can be sent to landroid_cloud (at) trab.dk - please write write 'Issue 381' somewhere in the subject

**Comment by GSzabados** [comment]
I will be able to send it in the evening. Thanks for looking at it.

**Comment by GSzabados** [comment]
I updated to 3.0.2 and there is a bit different error this time:

Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:391
First occurred: 02:24:47 (1 occurrences)
Last logged: 02:24:47

```
Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3330, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/mqtt.py", line 149, in _forward_on_message
    self._on_update(msg)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 353, in _on_update
    self._decode_data(device)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 382, in _decode_data
    device.rssi = data["dat"]["rsi"]
KeyError: 'rsi'

```

**Comment by MTrab** [comment]
Looks like your mower doesn't always send all information.

I'll try and put checks on all required data

**Comment by GSzabados** [comment]
I just sent you the credentials for the mower.

This error message might be different due to a missing wire error during the night, and the mower powered down caused by that, before this error.

**Comment by yack1** [comment]
landroid_cloud 3.0.2

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:206
Integration: Landroid Cloud (documentation, issues)
First occurred: 12:04:19 (2 occurrences)
Last logged: 12:29:10

Error setting up entry Worx -xxxxxxxxxxx@gmail.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
    await hass.async_add_executor_job(cloud.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 241, in connect
    self._fetch()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 564, in _fetch
    device = DeviceHandler(self._api, mower)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 46, in __init__
    self.__mapinfo(api, mower)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 100, in __mapinfo
    self.zone = Zone(data)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/zone.py", line 22, in __init__
    if not "payload" in data["last_status"]:
TypeError: argument of type 'NoneType' is not iterable

**Comment by GSzabados** [comment]
I've looked for it, but since I changed password and sent you the credentials it hasn't popped up. 

I have no idea what was causing it. But since the last one, the`rsi` one, there wasn't any. If you want, feel free to close it and once it comes again, I will ask to be reopened.

(To be honest, my educated guess would be that something was worked on in the cloud side. But it doesn't  make sense why this error happened always about the same time (between 2AM and 4AM) even in between restarts and reloads.)

**Comment by MTrab** [comment]
I'll leave it open for now. I'm currently putting in some checks for missing data and will close this issue with that release

**Comment by GSzabados** [comment]
I just updated the firmware recently to 3.30 and then the error popped up again.

```
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:391
First occurred: 15:23:07 (1 occurrences)
Last logged: 15:23:07

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3330, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/mqtt.py", line 149, in _forward_on_message
    self._on_update(msg)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 353, in _on_update
    self._decode_data(device)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 412, in _decode_data
    data["dat"]["modules"]["4G"]["gps"]["coo"][0],
KeyError: 'gps'

```

**Comment by GSzabados** [comment]
Actually the log matches the time when the mower recovered from the firmware update.

**Comment by GSzabados** [comment]
@MTrab, I just looked at my Log for another reason and just saw this in it:

```
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:391
First occurred: 07:15:21 (1 occurrences)
Last logged: 07:15:21

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3330, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/mqtt.py", line 149, in _forward_on_message
    self._on_update(msg)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 374, in _on_update
    self._decode_data(device)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 405, in _decode_data
    device.rssi = data["dat"]["rsi"]
KeyError: 'rsi'

```

**Comment by GSzabados** [comment]
The landroid had a wire missing error at 6:56:15 and probably powered down after that. I don't know that has my wife restarted/turned on since, probably not.

**Comment by GSzabados** [comment]
So, meanwhile I have restarted HA, and had the same error. And just recently restarted the Mower as well. The integration stayed on the error state and last refresh time as before, so the error stopped it as before the previous fix was implementation. After a final reloaded integration everything working again as normal.

**Comment by GSzabados** [comment]
Here is another new uncaught thread error:

```
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:399
First occurred: 07:22:57 (1 occurrences)
Last logged: 07:22:57

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3330, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/utils/mqtt.py", line 149, in _forward_on_message
    self._on_update(msg)
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 374, in _on_update
    self._decode_data(device)
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 421, in _decode_data
    device.locked = bool(data["dat"]["lk"])
                         ~~~~~~~~~~~^^^^^^
KeyError: 'lk'

```

**Comment by GSzabados** [comment]
Reloading the integration fails with this error message:

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:206
Integration: Landroid Cloud (documentation, issues)
First occurred: 19:52:00 (1 occurrences)
Last logged: 19:52:00

Error setting up entry configuration.yaml - ********@*******.*** for landroid_cloud

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
    result = await _async_setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
    await hass.async_add_executor_job(cloud.connect)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 259, in connect
    self._fetch()
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 624, in _fetch
    self._decode_data(device)
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 444, in _decode_data
    data["dat"]["modules"]["4G"]["gps"]["coo"][0],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'gps'

```

**Comment by GSzabados** [comment]
And on the second reload everything starts normally, without any error.

**Comment by GSzabados** [comment]
@MTrab, some uncaught exceptions are still failing the integration like this one below:

```
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:399
First occurred: 07:04:25 (1 occurrences)
Last logged: 07:04:25

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3330, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/utils/mqtt.py", line 149, in _forward_on_message
    self._on_update(msg)
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 374, in _on_update
    self._decode_data(device)
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 421, in _decode_data
    device.locked = bool(data["dat"]["lk"])
                         ~~~~~~~~~~~^^^^^^
KeyError: 'lk'

```

The mower stops responding and turns off with a wire missing error message and the integration never recovers by itself.
