### ISSUE TITLE
Error at Install

### ISSUE THREAD

**Issue by matejek** [MTrab/landroid_cloud#384]
### Describe the issue

2023-05-26 21:18:34.854 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration landroid_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-26 21:20:41.190 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - my@email.address for landroid_cloud
File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup

### What version of Home Assistant Core has the issue?

core-2023.5.4

### What was the last working version of Home Assistant Core?

core-2023.5.4

### What version of the Landroid Cloud integration do you have installed

v3.0.2

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid WG796E.1 and Worx Vision

### Diagnostics information (NOT log entries!)

see above

### Relevant log entries

```txt
none
```

**Comment by LaRisposta4** [comment]
I have the same issue

**Comment by MTrab** [comment]
Please open the home-assistant.log file and copy the full error.
This looks alot like error in email or password when setting up, althou this should be handled already.

**Comment by rabattcoupon** [comment]
I have the same error as well.

2023-05-30 10:15:28.421 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - mail@mail.mail for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
    await hass.async_add_executor_job(cloud.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 241, in connect
    self._fetch()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 564, in _fetch
    device = DeviceHandler(self._api, mower)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 46, in __init__
    self.__mapinfo(api, mower)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 100, in __mapinfo
    self.zone = Zone(data)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/zone.py", line 22, in __init__
    if not "payload" in data["last_status"]:
TypeError: argument of type 'NoneType' is not iterable

**Comment by MTrab** [comment]
Seems strange - that line should take care of exactly that issue :/

Do you mind sending your credentials to landroid_cloud (at) trab.dk with the text Issue 384 in the subject.
Then I'll do some debugging seeing why it's not handled correctly.

**Comment by MTrab** [comment]
That's okay.
Let's see if another user with the same problem can help

**Comment by MTrab** [comment]
Seems like #386 is the same issue

**Comment by MTrab** [comment]
Solved in v3.0.2
