### ISSUE TITLE
Landroid 3.0.2 not loaded in HA

### ISSUE THREAD

**Issue by frank-dusign** [MTrab/landroid_cloud#386]
### Describe the issue

Failure during load of Integration.
TypeError: argument of type 'NoneType' is not iterable

Would it be helpfull to receive the cloud access account data ?

### What version of Home Assistant Core has the issue?

2023.5.3

### What was the last working version of Home Assistant Core?

2023.5.3

### What version of the Landroid Cloud integration do you have installed

3.0.2

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

WR142E

### Diagnostics information (NOT log entries!)

Integration completely removed und reinstalled.

3 Mowers in the Worx Cloud
2 offline (WR111mi / WG796E.1) and 1 online (WR142E).

Last working Version 3.0.b5

### Relevant log entries

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
    await hass.async_add_executor_job(cloud.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 241, in connect
    self._fetch()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 564, in _fetch
    device = DeviceHandler(self._api, mower)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 46, in __init__
    self.__mapinfo(api, mower)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 100, in __mapinfo
    self.zone = Zone(data)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/zone.py", line 22, in __init__
    if not "payload" in data["last_status"]:
TypeError: argument of type 'NoneType' is not iterable
```

### Additional information

Version | core-2023.5.3
-- | --
Installationstyp | Home Assistant Container
Entwicklung | false
Supervisor | false
Docker | true
Benutzer | root
Virtuelle Umgebung | false
Python-Version | 3.10.11
Betriebssystemfamilie | Linux
Betriebssystem-Version | 4.19.0-24-amd64
CPU-Architektur | x86_64
Zeitzone | Europe/Berlin

**Comment by MTrab** [comment]
This issue should already be handled in the latest release.
Could you please share your credentials via landroid_cloud (at) trab.dk specifying issue 386 in the subject, then I'll do some debugging on why it's not handled as it should be.
