### ISSUE TITLE
Error setting up entry Worx - .... for landroid_cloud

### ISSUE THREAD

**Issue by frank-dusign** [MTrab/landroid_cloud#389]
### Describe the issue

Integration loads end with failure

last working version 3.0b5

### What version of Home Assistant Core has the issue?

2023.5.3

### What was the last working version of Home Assistant Core?

2023.5.3

### What version of the Landroid Cloud integration do you have installed

3.0.3

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

WR142E and some more, see #386

### Diagnostics information (NOT log entries!)

Error setting up entry Worx - .... for landroid_cloud

remove custom-files and integration, restart, reload Landroid and reset integration

### Relevant log entries

```txt
Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:206
Integration: Landroid Cloud (documentation, issues)
First occurred: 16:24:38 (3 occurrences)
Last logged: 16:28:08

Error setting up entry Worx - lahn@dusign.de for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
    await hass.async_add_executor_job(cloud.connect)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 259, in connect
    self._fetch()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 597, in _fetch
    device = DeviceHandler(self._api, mower)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 46, in __init__
    self.__mapinfo(api, mower)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/devices.py", line 100, in __mapinfo
    self.zone = Zone(data)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/zone.py", line 50, in __init__
    self["current"] = self["indicies"][self["index"]]
TypeError: list indices must be integers or slices, not NoneType
```

### Additional information

.

**Comment by Vannian** [comment]
having the same issue.

**Comment by JohnnyCarcinogen** [comment]
Same issue for me as well. Didn't realize it before I submitted my own issue. Do we still need the email/pw in the confiuration.yaml?

**Comment by MTrab** [comment]
> Do we still need the email/pw in the confiuration.yaml?

No

**Comment by JohnnyCarcinogen** [comment]
> > Do we still need the email/pw in the confiuration.yaml?
> 
> No

Good deal. I removed it as part of the cleanup.

**Comment by frank-dusign** [comment]
Hi Marlen,
I removed the two offline mowers from the cloud, the M700 Type runs well. One of the WR modells had a multizone setup, may be thats it. They will stay disconnected for a while,
So my account will probably not generate the bug now. (see #386 )

**Comment by MTrab** [comment]
This should be fixed in the next release
