### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by argonaute199** [MTrab/landroid_cloud#425]
### Describe the issue

Hi,
My integration doesn’t work anymore. It tried to remove the integration and the deposit, restart, reinstall it, but the configuration still fails.
I did not change anything in Home Assistant before the failure.
The official app still works, and I can see my mower on the cloud.
How can I know if I am banned ? Any other reasons ?
Thank you

### What version of Home Assistant Core has the issue?

2003.8

### What was the last working version of Home Assistant Core?

2003.8

### What version of the Landroid Cloud integration do you have installed

V3.0.5

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

WR142E

### Diagnostics information (NOT log entries!)

No option to download diagnostics

### Relevant log entries

```txt
Error setting up entry Worx - argo199@outlook.fr for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
    result = await _async_setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
    await hass.async_add_executor_job(cloud.connect)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 259, in connect
    self._fetch()
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 611, in _fetch
    self._mowers = self._api.get_mowers()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/api.py", line 119, in get_mowers
    mower["firmware_version"] = "{:.2f}".format(mower["firmware_version"])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'str'
```

**Comment by MTrab** [comment]
Update to latest version
