### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by erocm123** [MTrab/landroid_cloud#499]
### Describe the issue

Been having this issue for a few months now. Used to work back several months ago, but lately I have been getting an errort. I've tried the production release as well as beta and have just kind of been hoping it would get worked out. Logs look like the login works and data is returned but then there is a python error.

### What version of Home Assistant Core has the issue?

core-2023.12.0

### What version of the Landroid Cloud integration do you have installed

v4.0.0b4

### What type of installation are you running?

Home Assistant Container

### Which make and model is the mower used for this integration?

WR150 Landroid L1500

### Diagnostics information (NOT log entries!)

Not seeing the option in the drop down menu

### Relevant log entries

```txt
Jan 16 13:39:09 CentOS7 podman: 2024-01-16 13:39:09.264 INFO (MainThread) [custom_components.landroid_cloud]
Jan 16 13:39:09 CentOS7 podman: -------------------------------------------------------------------
Jan 16 13:39:09 CentOS7 podman: Landroid Cloud integration
Jan 16 13:39:09 CentOS7 podman: Version: 4.0.0b4
Jan 16 13:39:09 CentOS7 podman: This is a custom integration
Jan 16 13:39:09 CentOS7 podman: If you have any issues with this you need to open an issue here:
Jan 16 13:39:09 CentOS7 podman: https://github.com/mtrab/landroid_cloud/issues
Jan 16 13:39:09 CentOS7 podman: -------------------------------------------------------------------
Jan 16 13:39:09 CentOS7 podman: 
Jan 16 13:39:09 CentOS7 podman: 2024-01-16 13:39:09.264 DEBUG (MainThread) [custom_components.landroid_cloud] (Setup) Opening connection to Worx account for e******@gmail.com
Jan 16 13:39:09 CentOS7 podman: 2024-01-16 13:39:09.264 DEBUG (MainThread) [pyworxcloud] Initializing connector...
Jan 16 13:39:09 CentOS7 podman: 2024-01-16 13:39:09.264 DEBUG (MainThread) [pyworxcloud] Try getting correct CloudType from WORX
Jan 16 13:39:09 CentOS7 podman: 2024-01-16 13:39:09.264 DEBUG (MainThread) [pyworxcloud] Found cloud type <class 'pyworxcloud.clouds.CloudType.WORX'>
Jan 16 13:39:09 CentOS7 podman: 2024-01-16 13:39:09.264 DEBUG (MainThread) [pyworxcloud] Initializing the API connector ...
Jan 16 13:39:09 CentOS7 podman: 2024-01-16 13:39:09.264 DEBUG (MainThread) [pyworxcloud] Getting logger ...
Jan 16 13:39:09 CentOS7 podman: 2024-01-16 13:39:09.264 DEBUG (MainThread) [pyworxcloud] Initializing EventHandler ...
Jan 16 13:39:09 CentOS7 podman: 2024-01-16 13:39:09.265 DEBUG (SyncWorker_4) [pyworxcloud] Authenticating e******@gmail.com
Jan 16 13:39:10 CentOS7 podman: 2024/01/16 20:39:10 New tick of statistics from 10.37.20.23: 21519 ads blocked / 228136 total DNS queries
Jan 16 13:39:10 CentOS7 podman: 2024/01/16 20:39:10 New tick of statistics from 10.37.20.24: 0 ads blocked / 362 total DNS queries
Jan 16 13:39:10 CentOS7 podman: 2024-01-16 13:39:10.432 DEBUG (SyncWorker_4) [pyworxcloud] Authentication for e******@gmail.com successful
Jan 16 13:39:10 CentOS7 podman: 2024-01-16 13:39:10.432 DEBUG (SyncWorker_3) [pyworxcloud] Fetching basic API data
Jan 16 13:39:12 CentOS7 podman: 2024-01-16 13:39:12.097 DEBUG (SyncWorker_3) [pyworxcloud.utils.capability] Capability data: {'id': 465651, 'uuid': '96c52ec8-7161-4002-85c4-8c1c4f663542', 'product_id': 55, 'user_id': 363579, 'serial_number': '202030886801000129EB', 'mac_address': 'FCF5C44A639C', 'locked': False, 'firmware_version': '3.32.0+1', 'firmware_auto_upgrade': True, 'sim': {'id': 4861, 'iccid': '8944538523019051344', 'sim_status': 'provisioned', 'pending_activation': False, 'contract_starts_at': '2020-08-13 00:00:00', 'contract_ends_at': '2024-08-13 00:00:00', 'created_at': '2020-08-12 23:49:03', 'updated_at': '2024-01-15 22:00:52'}, 'test': False, 'iot_registered': True, 'mqtt_registered': True, 'registered_at': '2020-08-12 00:00:00', 'online': False, 'protocol': 0, 'pending_radio_link_validation': None, 'capabilities': ['auto_lock', 'bluetooth_pairing', 'border_cut', 'digital_fence_settings', 'follow_border', 'lock', 'mqtt', 'multi_zone', 'multi_zone_percentage', 'one_time_scheduler', 'ota_upgrade', 'pairing_smartconfig', 'pause_over_border', 'pause_over_wire', 'rain_delay', 'rain_delay_start', 'safe_go_home', 'scheduler_two_slots', 'unrestricted_mowing_time', 'zone_keeper'], 'capabilities_available': [], 'features': {'auto_lock': 3.25, 'bluetooth_pairing': True, 'chassis': 'l_2019', 'digital_fence_settings': 3.25, 'display_type': 'lcd', 'input_type': 'keyboard_arrow_keys', 'lock': True, 'mqtt': True, 'multi_zone': True, 'multi_zone_percentage': True, 'multi_zone_zones': 4, 'one_time_scheduler': 3.15, 'pause_over_wire': 3.26, 'rain_delay': True, 'rain_delay_start': 3.08, 'safe_go_home': 3.25, 'scheduler_two_slots': 3.15, 'unrestricted_mowing_time': True, 'wifi_pairing': 'smartconfig'}, 'accessories': {'cellular': True}, 'mqtt_endpoint': 'iot.eu-west-1.worxlandroid.com', 'mqtt_topics': {'command_in': 'PRM100/FCF5C44A639C/commandIn', 'command_out': 'PRM100/FCF5C44A639C/commandOut'}, 'name': 'Landroid', 'blade_height_shift': 0, 'push_notifications': True, 'push_notifications_level': 'warning', 'pin_code': 'CADB', 'app_settings': {'cellular_setup_completed': True}, 'warranty_registered': True, 'purchased_at': '2020-08-02 00:00:00', 'warranty_expires_at': '2023-08-02 00:00:00', 'setup_location': {'latitude': 41.142585, 'longitude': -111.9653536}, 'city': {'id': 5784384, 'country_id': 840, 'name': 'Washington Terrace', 'latitude': 41.172722, 'longitude': -111.976608, 'created_at': '2018-02-15 22:59:39', 'updated_at': '2018-02-15 22:59:39'}, 'time_zone': 'America/Denver', 'lawn_size': 263.04607353149, 'lawn_perimeter': 91, 'auto_schedule_settings': {'boost': 0, 'exclusion_scheduler': {'days': [{'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}, {'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}, {'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}, {'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}, {'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}, {'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}, {'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}], 'exclude_nights': True}, 'grass_type': 'poa_pratensis', 'irrigation': True, 'nutrition': None, 'soil_type': 'silt'}, 'auto_schedule': True, 'improvement': True, 'diagnostic': True, 'distance_covered': 569140, 'mower_work_time': 38811, 'blade_work_time': 36667, 'blade_work_time_reset': 0, 'blade_work_time_reset_at': None, 'battery_charge_cycles': 406, 'battery_charge_cycles_reset': 0, 'battery_charge_cycles_reset_at': None, 'created_at': '2020-02-26 05:00:04', 'updated_at': '2023-08-23 01:36:19', 'last_status': {'timestamp': '2023-10-29 23:09:06', 'payload': {'cfg': {'id': 0, 'sn': '202030886801000129EB', 'dt': '29/10/2023', 'tm': '17:09:10', 'lg': 'en', 'cmd': 0, 'sc': {'m': 2, 'd': [['11:00', 30, 1], ['11:00', 30, 0], ['11:00', 30, 1], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0]], 'dd': [['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0]], 'distm': 0, 'p': 0, 'ots': {'wtm': 0, 'bc': 0}}, 'mz': [0, 0, 0, 0], 'mzv': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'mzk': 0, 'rd': 120, 'al': {'lvl': 0, 't': 60}, 'tq': 0, 'modules': {'4G': {'enabled': 1, 'geo': {'coo': [41.142609, -111.965218], 'rad': 24}}}}, 'dat': {'mac': 'FCF5C44A639C', 'fw': 3.32, 'fwb': 1, 'ls': 1, 'le': 0, 'conn': '4G', 'bt': {'t': 17.6, 'v': 19.87, 'p': 100, 'nr': 406, 'c': 0, 'm': 1}, 'dmp': [1.4, 1.1, 359.9], 'st': {'b': 36667, 'd': 569140, 'wt': 38811, 'bl': 91}, 'act': 1, 'rsi': 0, 'lk': 0, 'tr': 0, 'lz': 0, 'rain': {'s': 0, 'cnt': 0}, 'modules': {'4G': {'stat': 'ok', 'vers': 2.55, 'batt': {'t': 19, 'v': 4.11, 'l': 96}, 'mode': 1, 'geo': {'stat': 'unk'}, 'network': {'status': 'connected', 'mode': 'EDGE', 'ICCID': '8944538523019051344', 'IMSI': '204080748039118', 'rssi': -66}}}}}}, 'model': {'code': 'WR150', 'friendly_name': 'Landroid L1500', 'model_year': 2019, 'cutting_width': 220}}
Jan 16 13:39:12 CentOS7 podman: 2024-01-16 13:39:12.098 DEBUG (SyncWorker_3) [pyworxcloud] Mower 'Landroid' data: {'id': 465651, 'uuid': '96c52ec8-7161-4002-85c4-8c1c4f663542', 'product_id': 55, 'user_id': 363579, 'serial_number': '202030886801000129EB', 'mac_address': 'FCF5C44A639C', 'locked': False, 'firmware_version': '3.32.0+1', 'firmware_auto_upgrade': True, 'sim': {'id': 4861, 'iccid': '8944538523019051344', 'sim_status': 'provisioned', 'pending_activation': False, 'contract_starts_at': '2020-08-13 00:00:00', 'contract_ends_at': '2024-08-13 00:00:00', 'created_at': '2020-08-12 23:49:03', 'updated_at': '2024-01-15 22:00:52'}, 'test': False, 'iot_registered': True, 'mqtt_registered': True, 'registered_at': '2020-08-12 00:00:00', 'online': False, 'protocol': 0, 'pending_radio_link_validation': None, 'capabilities': ['auto_lock', 'bluetooth_pairing', 'border_cut', 'digital_fence_settings', 'follow_border', 'lock', 'mqtt', 'multi_zone', 'multi_zone_percentage', 'one_time_scheduler', 'ota_upgrade', 'pairing_smartconfig', 'pause_over_border', 'pause_over_wire', 'rain_delay', 'rain_delay_start', 'safe_go_home', 'scheduler_two_slots', 'unrestricted_mowing_time', 'zone_keeper'], 'capabilities_available': [], 'features': {'auto_lock': 3.25, 'bluetooth_pairing': True, 'chassis': 'l_2019', 'digital_fence_settings': 3.25, 'display_type': 'lcd', 'input_type': 'keyboard_arrow_keys', 'lock': True, 'mqtt': True, 'multi_zone': True, 'multi_zone_percentage': True, 'multi_zone_zones': 4, 'one_time_scheduler': 3.15, 'pause_over_wire': 3.26, 'rain_delay': True, 'rain_delay_start': 3.08, 'safe_go_home': 3.25, 'scheduler_two_slots': 3.15, 'unrestricted_mowing_time': True, 'wifi_pairing': 'smartconfig'}, 'accessories': {'cellular': True}, 'mqtt_endpoint': 'iot.eu-west-1.worxlandroid.com', 'mqtt_topics': {'command_in': 'PRM100/FCF5C44A639C/commandIn', 'command_out': 'PRM100/FCF5C44A639C/commandOut'}, 'name': 'Landroid', 'blade_height_shift': 0, 'push_notifications': True, 'push_notifications_level': 'warning', 'pin_code': 'CADB', 'app_settings': {'cellular_setup_completed': True}, 'warranty_registered': True, 'purchased_at': '2020-08-02 00:00:00', 'warranty_expires_at': '2023-08-02 00:00:00', 'setup_location': {'latitude': 41.142585, 'longitude': -111.9653536}, 'city': {'id': 5784384, 'country_id': 840, 'name': 'Washington Terrace', 'latitude': 41.172722, 'longitude': -111.976608, 'created_at': '2018-02-15 22:59:39', 'updated_at': '2018-02-15 22:59:39'}, 'time_zone': 'America/Denver', 'lawn_size': 263.04607353149, 'lawn_perimeter': 91, 'auto_schedule_settings': {'boost': 0, 'exclusion_scheduler': {'days': [{'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}, {'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}, {'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}, {'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}, {'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}, {'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}, {'slots': [{'reason': 'generic', 'duration': 600, 'start_time': 0}, {'reason': 'generic', 'duration': 525, 'start_time': 900}, {'reason': 'irrigation', 'duration': 165, 'start_time': 1260}], 'exclude_day': False}], 'exclude_nights': True}, 'grass_type': 'poa_pratensis', 'irrigation': True, 'nutrition': None, 'soil_type': 'silt'}, 'auto_schedule': True, 'improvement': True, 'diagnostic': True, 'distance_covered': 569140, 'mower_work_time': 38811, 'blade_work_time': 36667, 'blade_work_time_reset': 0, 'blade_work_time_reset_at': None, 'battery_charge_cycles': 406, 'battery_charge_cycles_reset': 0, 'battery_charge_cycles_reset_at': None, 'created_at': '2020-02-26 05:00:04', 'updated_at': '2023-08-23 01:36:19', 'last_status': {'timestamp': '2023-10-29 23:09:06', 'payload': {'cfg': {'id': 0, 'sn': '202030886801000129EB', 'dt': '29/10/2023', 'tm': '17:09:10', 'lg': 'en', 'cmd': 0, 'sc': {'m': 2, 'd': [['11:00', 30, 1], ['11:00', 30, 0], ['11:00', 30, 1], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0]], 'dd': [['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0]], 'distm': 0, 'p': 0, 'ots': {'wtm': 0, 'bc': 0}}, 'mz': [0, 0, 0, 0], 'mzv': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'mzk': 0, 'rd': 120, 'al': {'lvl': 0, 't': 60}, 'tq': 0, 'modules': {'4G': {'enabled': 1, 'geo': {'coo': [41.142609, -111.965218], 'rad': 24}}}}, 'dat': {'mac': 'FCF5C44A639C', 'fw': 3.32, 'fwb': 1, 'ls': 1, 'le': 0, 'conn': '4G', 'bt': {'t': 17.6, 'v': 19.87, 'p': 100, 'nr': 406, 'c': 0, 'm': 1}, 'dmp': [1.4, 1.1, 359.9], 'st': {'b': 36667, 'd': 569140, 'wt': 38811, 'bl': 91}, 'act': 1, 'rsi': 0, 'lk': 0, 'tr': 0, 'lz': 0, 'rain': {'s': 0, 'cnt': 0}, 'modules': {'4G': {'stat': 'ok', 'vers': 2.55, 'batt': {'t': 19, 'v': 4.11, 'l': 96}, 'mode': 1, 'geo': {'stat': 'unk'}, 'network': {'status': 'connected', 'mode': 'EDGE', 'ICCID': '8944538523019051344', 'IMSI': '204080748039118', 'rssi': -66}}}}}}, 'model': {'code': 'WR150', 'friendly_name': 'Landroid L1500', 'model_year': 2019, 'cutting_width': 220}}
Jan 16 13:39:12 CentOS7 podman: 2024-01-16 13:39:12.098 DEBUG (SyncWorker_3) [pyworxcloud.decode_data] Data decoding for Landroid started
Jan 16 13:39:12 CentOS7 podman: 2024-01-16 13:39:12.098 DEBUG (SyncWorker_3) [pyworxcloud.decode_data] Found raw data: {'cfg': {'id': 0, 'sn': '202030886801000129EB', 'dt': '29/10/2023', 'tm': '17:09:10', 'lg': 'en', 'cmd': 0, 'sc': {'m': 2, 'd': [['11:00', 30, 1], ['11:00', 30, 0], ['11:00', 30, 1], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0]], 'dd': [['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0], ['00:00', 0, 0]], 'distm': 0, 'p': 0, 'ots': {'wtm': 0, 'bc': 0}}, 'mz': [0, 0, 0, 0], 'mzv': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'mzk': 0, 'rd': 120, 'al': {'lvl': 0, 't': 60}, 'tq': 0, 'modules': {'4G': {'enabled': 1, 'geo': {'coo': [41.142609, -111.965218], 'rad': 24}}}}, 'dat': {'mac': 'FCF5C44A639C', 'fw': 3.32, 'fwb': 1, 'ls': 1, 'le': 0, 'conn': '4G', 'bt': {'t': 17.6, 'v': 19.87, 'p': 100, 'nr': 406, 'c': 0, 'm': 1}, 'dmp': [1.4, 1.1, 359.9], 'st': {'b': 36667, 'd': 569140, 'wt': 38811, 'bl': 91}, 'act': 1, 'rsi': 0, 'lk': 0, 'tr': 0, 'lz': 0, 'rain': {'s': 0, 'cnt': 0}, 'modules': {'4G': {'stat': 'ok', 'vers': 2.55, 'batt': {'t': 19, 'v': 4.11, 'l': 96}, 'mode': 1, 'geo': {'stat': 'unk'}, 'network': {'status': 'connected', 'mode': 'EDGE', 'ICCID': '8944538523019051344', 'IMSI': '204080748039118', 'rssi': -66}}}}}
Jan 16 13:39:12 CentOS7 podman: 2024-01-16 13:39:12.098 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - e******@gmail.com for landroid_cloud
Jan 16 13:39:12 CentOS7 podman: Traceback (most recent call last):
Jan 16 13:39:12 CentOS7 podman: File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
Jan 16 13:39:12 CentOS7 podman: result = await component.async_setup_entry(hass, self)
Jan 16 13:39:12 CentOS7 podman: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 16 13:39:12 CentOS7 podman: File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
Jan 16 13:39:12 CentOS7 podman: result = await _async_setup(hass, entry)
Jan 16 13:39:12 CentOS7 podman: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 16 13:39:12 CentOS7 podman: File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
Jan 16 13:39:12 CentOS7 podman: await hass.async_add_executor_job(cloud.connect)
Jan 16 13:39:12 CentOS7 podman: File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Jan 16 13:39:12 CentOS7 podman: result = self.fn(*self.args, **self.kwargs)
Jan 16 13:39:12 CentOS7 podman: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 16 13:39:12 CentOS7 podman: File "/config/deps/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 260, in connect
Jan 16 13:39:12 CentOS7 podman: self._fetch()
Jan 16 13:39:12 CentOS7 podman: File "/config/deps/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 689, in _fetch
Jan 16 13:39:12 CentOS7 podman: self._decode_data(device)
Jan 16 13:39:12 CentOS7 podman: File "/config/deps/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 469, in _decode_data
Jan 16 13:39:12 CentOS7 podman: data["dat"]["modules"]["4G"]["gps"]["coo"][0],
Jan 16 13:39:12 CentOS7 podman: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
Jan 16 13:39:12 CentOS7 podman: KeyError: 'gps'
```

**Comment by MTrab** [comment]
Either you are not on the latest version, else your mower doesn't send GPS location for some reason.

**Comment by erocm123** [comment]
Do you mean the latest version of Worx firmware? Anyway I can check to see what the GPS data looks like from the mower? Maybe just check it out in the app to see if it is showing?

**Comment by erocm123** [comment]
Well I started up the mower and opened the "Find my landroid" in the app and was able to reload the integration afterwards without error. So looks like this is resolved. Thanks for the help.
