### ISSUE TITLE
Error while setting up landroid_cloud platform

### ISSUE THREAD

**Issue by Comaglove** [MTrab/landroid_cloud#5]
Logginformation (ERROR)
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:423
Integration: Sensor (documentation, issues)
First occurred: 9:45:34 (1 occurrences)
Last logged: 9:45:34

Error while setting up landroid_cloud platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 423, in _async_add_entity
    raise HomeAssistantError(f"Invalid entity id: {entity.entity_id}")
homeassistant.exceptions.HomeAssistantError: Invalid entity id: sensor.landroid_emils klippare_battery

Can you help with this, thanks?

**Comment by MTrab** [comment]
This will be fixed in next update (which I hope will be available within a few days) - it's because you have a whitespace in the name ;)

**Comment by Comaglove** [comment]
Thank you!
