### ISSUE TITLE
Error with landroid_cloud on HA 0.117

### ISSUE THREAD

**Issue by rosscullen** [MTrab/landroid_cloud#52]
Upgraded today to the latest Home Assistant 0.117 (28/10/2020) and error occurring with integration:

Logger: homeassistant.setup
Source: custom_components/landroid_cloud/__init__.py:264
First occurred: 9:46:57 PM (1 occurrences)
Last logged: 9:46:57 PM

Error during setup of component landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/landroid_cloud/__init__.py", line 126, in async_setup
    await api.async_force_update()
  File "/config/custom_components/landroid_cloud/__init__.py", line 264, in async_force_update
    await self._hass.async_add_executor_job(self._client.getStatus)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyworxcloud/__init__.py", line 152, in getStatus
    self._decodeData(status)
  File "/usr/local/lib/python3.8/site-packages/pyworxcloud/__init__.py", line 158, in _decodeData
    self.rssi = data['dat']['rsi']
KeyError: 'dat'

**Comment by MTrab** [comment]
Unfortunately I don't have access to an account for Worx anymore (moved to an appartment and don't have a Worx device anymore)

I'll see if I can gain access to a friends account for further development and bug-fixing.

**Comment by rosscullen** [comment]
Thanks @MTrab, hope your settling into your new apartment ok. It may be just my unit lets see will anyone else report similar issue(s). If its any help, i'm happy to share my account details with you. Thanks as always!

**Comment by MuppetOwl** [comment]
Can also confirm same issue with 0.117 and 0.117.1

Logger: homeassistant.setup
Source: custom_components/landroid_cloud/__init__.py:264
First occurred: 11:54:43 (1 occurrences)
Last logged: 11:54:43

Error during setup of component landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/landroid_cloud/__init__.py", line 126, in async_setup
    await api.async_force_update()
  File "/config/custom_components/landroid_cloud/__init__.py", line 264, in async_force_update
    await self._hass.async_add_executor_job(self._client.getStatus)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyworxcloud/__init__.py", line 152, in getStatus
    self._decodeData(status)
  File "/usr/local/lib/python3.8/site-packages/pyworxcloud/__init__.py", line 158, in _decodeData
    self.rssi = data['dat']['rsi']
KeyError: 'dat'

**Comment by MuppetOwl** [comment]
Its back online again now. I was logged out from the Android Phone app to, so I had to log in again. And after I started the Landroid again and Home Assistant it started working again. So think this was most likely Worx doing some server maintenance.

**Comment by mikibo** [comment]
I have the same problem. But it happens only if mower is offline (not connected to internet).

**Comment by rosscullen** [comment]
Phew... good to know I'm not alone. Thanks everyone for feedback. 

I've my Landroid put away for the winter so will find out in March 2021! Closing this issue.
