### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by JayRHa** [MTrab/landroid_cloud#55]
Logger: homeassistant.setup
Source: custom_components/landroid_cloud/__init__.py:264
First occurred: 8:27:53 (1 occurrences)
Last logged: 8:27:53

Error during setup of component landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/landroid_cloud/__init__.py", line 126, in async_setup
    await api.async_force_update()
  File "/config/custom_components/landroid_cloud/__init__.py", line 264, in async_force_update
    await self._hass.async_add_executor_job(self._client.getStatus)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyworxcloud/__init__.py", line 152, in getStatus
    self._decodeData(status)
  File "/usr/local/lib/python3.8/site-packages/pyworxcloud/__init__.py", line 158, in _decodeData
    self.rssi = data['dat']['rsi']
KeyError: 'dat'

**Comment by MTrab** [comment]
Same as #53

**Comment by MTrab** [comment]
And fixed in 1.6.5
