### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by azazel1103** [MTrab/landroid_cloud#551]
### Describe the issue

Hi!

Just started the mower. Then looked at the integration and the message was: "Failed to set up". Any idea on how to debug this?

Worked well all last summer. 

### What version of Home Assistant Core has the issue?

core-2024.3.3

### What was the last working version of Home Assistant Core?

none from some 2023.8;

### What version of the Landroid Cloud integration do you have installed

3.0.5

### What type of installation are you running?

Home Assistant Core

### Which make and model is the mower used for this integration?

Worx WR142E

### Diagnostics information (NOT log entries!)

Version: 3.0.5
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/mtrab/landroid_cloud/issues
-------------------------------------------------------------------

2024-03-31 22:33:19.103 DEBUG (MainThread) [custom_components.landroid_cloud] (Setup) Opening connection to Worx account for m.i@g.com
2024-03-31 22:33:19.103 DEBUG (MainThread) [pyworxcloud] Initializing connector...
2024-03-31 22:33:19.103 DEBUG (MainThread) [pyworxcloud] Try getting correct CloudType from WORX
2024-03-31 22:33:19.103 DEBUG (MainThread) [pyworxcloud] Found cloud type <class 'pyworxcloud.clouds.CloudType.WORX'>
2024-03-31 22:33:19.103 DEBUG (MainThread) [pyworxcloud] Initializing the API connector ...
2024-03-31 22:33:19.103 DEBUG (MainThread) [pyworxcloud] Getting logger ...
2024-03-31 22:33:19.103 DEBUG (MainThread) [pyworxcloud] Initializing EventHandler ...
2024-03-31 22:33:19.103 DEBUG (SyncWorker_36) [pyworxcloud] Authenticating m.i@g.com
2024-03-31 22:33:19.702 DEBUG (SyncWorker_36) [pyworxcloud] Authentication for m.i@g.com successful
2024-03-31 22:33:19.702 DEBUG (SyncWorker_22) [pyworxcloud] Fetching basic API data
2024-03-31 22:33:20.244 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - m.i@g.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
  File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyworxcloud/__init__.py", line 259, in connect
    self._fetch()
  File "/usr/local/lib/python3.12/site-packages/pyworxcloud/__init__.py", line 611, in _fetch
    self._mowers = self._api.get_mowers()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyworxcloud/api.py", line 119, in get_mowers
    mower["firmware_version"] = "{:.2f}".format(mower["firmware_version"])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'str'

### Relevant log entries

```txt
Version: 3.0.5
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/mtrab/landroid_cloud/issues
-------------------------------------------------------------------

2024-03-31 22:33:19.103 DEBUG (MainThread) [custom_components.landroid_cloud] (Setup) Opening connection to Worx account for m.i@g.com
2024-03-31 22:33:19.103 DEBUG (MainThread) [pyworxcloud] Initializing connector...
2024-03-31 22:33:19.103 DEBUG (MainThread) [pyworxcloud] Try getting correct CloudType from WORX
2024-03-31 22:33:19.103 DEBUG (MainThread) [pyworxcloud] Found cloud type <class 'pyworxcloud.clouds.CloudType.WORX'>
2024-03-31 22:33:19.103 DEBUG (MainThread) [pyworxcloud] Initializing the API connector ...
2024-03-31 22:33:19.103 DEBUG (MainThread) [pyworxcloud] Getting logger ...
2024-03-31 22:33:19.103 DEBUG (MainThread) [pyworxcloud] Initializing EventHandler ...
2024-03-31 22:33:19.103 DEBUG (SyncWorker_36) [pyworxcloud] Authenticating m.i@g.com
2024-03-31 22:33:19.702 DEBUG (SyncWorker_36) [pyworxcloud] Authentication for m.i@g.com successful
2024-03-31 22:33:19.702 DEBUG (SyncWorker_22) [pyworxcloud] Fetching basic API data
2024-03-31 22:33:20.244 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - m.i@g.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
  File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyworxcloud/__init__.py", line 259, in connect
    self._fetch()
  File "/usr/local/lib/python3.12/site-packages/pyworxcloud/__init__.py", line 611, in _fetch
    self._mowers = self._api.get_mowers()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyworxcloud/api.py", line 119, in get_mowers
    mower["firmware_version"] = "{:.2f}".format(mower["firmware_version"])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'str'
```

**Comment by MTrab** [comment]
Please upgrade to the latest version

**Comment by azazel1103** [comment]
Worked! Was doing the upgrade as you probably typing the solution.

 

TY
