### ISSUE TITLE
No entities/sensors created

### ISSUE THREAD

**Issue by clgjerstad** [MTrab/landroid_cloud#58]
Hi,

After installing through HACS and entering username/password into config.yaml, no landroid entities are created. Hence, the sensors never show up.  Any idea what I might be doing wrong.

Regards,
Chris

**Comment by MTrab** [comment]
Turn on you landroid if it's offline.
Worx purges all data after some time offline.

**Comment by clgjerstad** [comment]
By turning on, do you mean turning on the power? Or starting a cut? Because the landroid has been powered on the whole time I have tried.

**Comment by MTrab** [comment]
Just turn on the power, and make sure there are wifi connection.
What does the logs say?

**Comment by clgjerstad** [comment]
Here is the log:

Setup of landroid_cloud is taking longer than 300 seconds. Startup will proceed without waiting any longer
18:27:10 – setup.py (ERROR)
Waiting on integrations to complete setup: landroid_cloud
18:27:10 – bootstrap.py (WARNING) - meldingen oppstod først ved 18:23:10 og vist 5 ganger
Timeout fetching tesla data
18:23:55 – Tesla (ERROR)
Setup of landroid_cloud is taking over 10 seconds.
18:22:20 – /usr/local/lib/python3.8/asyncio/events.py (WARNING)

It seems it is also messing up my Tesla integration, as this normally works just fine. Any ideas?

**Comment by MTrab** [comment]
Unfortunately not - and currently I don't have a Landroid myself, so pretty difficult to investigate.

You could try putting this in your configuration.yaml, to see if that will reveal anything in the logs:

```
logger:
  default: info
  logs:
    custom_components.landroid_cloud: debug
```

**Comment by MTrab** [comment]
Any news?

**Comment by IngoHoh** [comment]
I have maybe the same problem here. No services where created. Entities are shown and were updated. Controlled it while landroid is mowing.

I added the debug mode in configuration.yaml but the only error wich is shown is:
2021-05-05 09:37:58 WARNING (MainThread) [homeassistant.setup] Setup of landroid_cloud is taking over 10 seconds.

**Comment by MTrab** [comment]
It must be a local problem - I'm running it on my own box, and I just last week setup the integration on a friends box, without any issues.

**Comment by IngoHoh** [comment]
thx for the quick reply.
I,ve already reinstalled the plugin many times but i didn't get those services. :-(

Doi have to fill the ID of the landroid in the services.yaml?

**Comment by MTrab** [comment]
No - services.yaml is NOT to be edited.

**Comment by MTrab** [comment]
And you are sure you don't see these service? 
![image](https://user-images.githubusercontent.com/14296463/117110958-32d5e180-ad87-11eb-99c6-625a7a86a4c8.png)

**Comment by IngoHoh** [comment]
Ok i let the services.yaml untouched.

Yes it's sure
![image](https://user-images.githubusercontent.com/83638776/117111785-6b29ef80-ad88-11eb-9cb2-81ac63dd69bb.png)

**Comment by MTrab** [comment]
But that's not services you are showing in that picture - that looks like your entity register.
The current version doesn't create entities in the registry, look under developer tools > states and search for landroid in that list.

**Comment by IngoHoh** [comment]
Sorry you're right.
Could it be the name of my Landroid with the "ä"?  But with the sensors there isn't a problem.

![image](https://user-images.githubusercontent.com/83638776/117112406-4bdf9200-ad89-11eb-9b8c-e29140031b26.png)

**Comment by MTrab** [comment]
No - services and names have nothing in common.

Could you try searching for landroid under developer tools > services?

**Comment by IngoHoh** [comment]
and here they are......
![image](https://user-images.githubusercontent.com/83638776/117112883-04a5d100-ad8a-11eb-8b11-ae31b76efe86.png)

**Comment by MTrab** [comment]
Great - so no problems then :)

**Comment by IngoHoh** [comment]
Damn.....
Sorry for that annoyance..... ;-)

**Comment by maury77** [comment]
Sorry but i have the similar problem but 

- I dont's see service landroid
- I restart the mover 

but the addons doesn't connect to landroid




[custom_components.landroid_cloud] Connecting to device ID 0 (mau....

2021-05-26 23:32:33 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: landroid_cloud
2021-05-26 23:32:41 ERROR (MainThread) [homeassistant.setup] Setup of landroid_cloud is taking longer than 300 seconds. Startup will proceed without waiting any longer

**Comment by simistef** [comment]
Hi, i am having the same problem. Entities not created for Landroid Cloud. Added the debun info in configuration.yaml and the only error i get is this:

Logger: homeassistant
Source: config_entries.py:542 
First occurred: 10:52:25 (1 occurrences) 
Last logged: 10:52:25

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/config_entries.py", line 535, in async_create_flow
    integration.get_platform("config_flow")
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/loader.py", line 424, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/loader.py", line 429, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/var/packages/python38/target/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/apple_tv/__init__.py", line 6, in <module>
    from pyatv import connect, exceptions, scan
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/pyatv/__init__.py", line 11, in <module>
    from pyatv.airplay import AirPlayStreamAPI
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/pyatv/airplay/__init__.py", line 17, in <module>
    from pyatv.airplay.srp import SRPAuthHandler
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/pyatv/airplay/srp.py", line 16, in <module>
    from srptools import SRPContext, SRPClientSession, constants
ModuleNotFoundError: No module named 'srptools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 119, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/config_entries.py", line 542, in async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler

**Comment by simistef** [comment]
actually the only entities created are 
<img width="1159" alt="Screenshot 2021-06-23 at 10 54 56" src="https://user-images.githubusercontent.com/2674401/123058480-8a9cda80-d411-11eb-9b72-c6cde932e3f5.png">

**Comment by MTrab** [comment]
And that's totally correct - see the readme. These are the only entities created.

**Comment by maijo366** [comment]
Hello MTrab, great Work!!!
But my Screen looks so an shows: 
![grafik](https://user-images.githubusercontent.com/96180786/148977975-687ae07d-486f-4745-a69a-aa55dd566392.png)
![grafik](https://user-images.githubusercontent.com/96180786/148978150-356838d5-18aa-4495-8d51-7b5d0183959d.png)

**Comment by MTrab** [comment]
Wild guess - your mower is turned off?
