### ISSUE TITLE
CertificateError: hostname 'api.worxlandroid.com' doesn't match '*.eu-west-1.es.amazonaws.com'

### ISSUE THREAD

**Issue by maxicasa** [MTrab/landroid_cloud#691]
### Describe the issue

Sometimes (I don't understand when this happens) the authentication of the integration fails: 
![image](https://github.com/user-attachments/assets/fe3256fc-b107-4c7c-98b3-43c154114413)

Only way to solve the issue is login/open the Landroid app and reload the integration (why?).

### What version of Home Assistant Core has the issue?

core-2024.9.1

### What version of the Landroid Cloud integration do you have installed

5.0.6

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Worx Landroid WR167E

### Diagnostics information (NOT log entries!)

[config_entry-landroid_cloud-0bfd252f9b4e6d083d06a77a09d1d3f1.json](https://github.com/user-attachments/files/16927959/config_entry-landroid_cloud-0bfd252f9b4e6d083d06a77a09d1d3f1.json)

### Relevant log entries

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: September 8, 2024 at 14:19:31 (1 occurrences)
Last logged: September 8, 2024 at 14:19:31

Error setting up entry Worx - ****@**** for landroid_cloud
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 472, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 545, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/ssl_match_hostname.py", line 155, in match_hostname
    raise CertificateError("hostname %r doesn't match %r" % (hostname, dnsnames[0]))
urllib3.util.ssl_match_hostname.CertificateError: hostname 'api.worxlandroid.com' doesn't match '*.eu-west-1.es.amazonaws.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.worxlandroid.com', port=443): Max retries exceeded with url: /api/v2/product-items?status=1 (Caused by SSLError(CertificateError("hostname 'api.worxlandroid.com' doesn't match '*.eu-west-1.es.amazonaws.com'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 207, in _async_setup
    await hass.async_add_executor_job(cloud.connect)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyworxcloud/__init__.py", line 263, in connect
    self._fetch()
  File "/usr/local/lib/python3.12/site-packages/pyworxcloud/__init__.py", line 692, in _fetch
    self._mowers = self._api.get_mowers()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyworxcloud/api.py", line 109, in get_mowers
    mowers = GET(
             ^^^^
  File "/usr/local/lib/python3.12/site-packages/pyworxcloud/utils/requests.py", line 96, in GET
    req = requests.get(
          ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.worxlandroid.com', port=443): Max retries exceeded with url: /api/v2/product-items?status=1 (Caused by SSLError(CertificateError("hostname 'api.worxlandroid.com' doesn't match '*.eu-west-1.es.amazonaws.com'")))
```

**Comment by MTrab** [comment]
Is this still an issue?

**Comment by maxicasa** [comment]
Seems not, but randomly happen. I think it's possible to close the issue.
