### ISSUE TITLE
Integration fails on startup

### ISSUE THREAD

**Issue by yolani** [MTrab/landroid_cloud#78]
Hi,

just bought a android (W165E) and tried to setup the integration on Home-Assistant  2021.10.4. It fails with the following exception during setup.

'''
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
    result = await task
  File "/config/custom_components/landroid_cloud/__init__.py", line 131, in async_setup
    await api.async_force_update()
  File "/config/custom_components/landroid_cloud/__init__.py", line 269, in async_force_update
    await self._hass.async_add_executor_job(self._client.getStatus)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 155, in getStatus
    self._decodeData(status)
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 168, in _decodeData
    self.error_description = ErrorDict[data['dat']['le']]
KeyError: 19
'''

**Comment by yolani** [comment]
I think I found the issue, error code "19" is probably something like "Battery compartment open". I just noticed that my app is displaying a warning like this, closed the lid and now the integration works

**Comment by MTrab** [comment]
Will be fixed in next release
