### ISSUE TITLE
Can't set next zone to be mowed

### ISSUE THREAD

**Issue by Barma-lej** [MTrab/landroid_cloud#98]
There is an issue with the cutting area set https://github.com/Barma-lej/halandroid/issues/42

You can only pass a parameter as a string when the parameter is explicitly specified. You cannot pass a parameter as a string if its value is taken from a template.
Could you convert integer to string in this line: `msg = '{"mz":' + zone + '}`
For example: `msg = '{"mz":' + str(zone) + '}`

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/landroid_cloud/__init__.py:306
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 13:17:06 (2 occurrences)
Last logged: 13:17:14

[139697368341616] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 630, in handle_execute_script await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1275, in async_run await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in async_run await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/landroid_cloud/__init__.py", line 306, in handle_setzone cli.setZone(call.data["zone"])
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 327, in setZone msg = '{"mz":' + zone + '}'
TypeError: can only concatenate str (not "int") to str
```

**Comment by MTrab** [comment]
Please check the newly released beta version if that works.
Haven't had the possibility to test this fix myself

**Comment by Barma-lej** [comment]
It works. At least no error appears.
Thanks

**Comment by infohannes** [comment]
Hello Morton,
Hello Barma-lej,
Sorry, but I want to ask again, regarding my problem with selecting from multiple zones via Barmalej's frontend input selector.
It would be nice if someone could help me here.☺ I don't know if I'm the only one having this problem...
I still get the same error even after your update to 1.8.5:

_File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service await cast(Callable[[ServiceCall], waitable[None]], handler.job.target)(
File "/config/custom_components/landroid_cloud/init.py", line 351, in handle_setzone
cli.setZone(call.data["zone"])
File "/usr/local/lib/python3.9/site-packages/pyworxcloud/init.py", line 327, in setZone
msg = '{"mz":' + zone + '}'
**TypeError: can only concatenate str (not "int") to str_**

here is my description of this fault: script error set multizone Barma-lej/halandroid#42 
here is my System configuration: 
## System Health
version | core-2022.4.5
-- | --
installation_type | Home Assistant OS
hassio | true
docker | true
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | Europe/Berlin
host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9

**Comment by MTrab** [comment]
I'm on Easter holiday, so cannot help right now

**Comment by MTrab** [comment]
Neither calling this

```
service: landroid_cloud.setzone
data:
  zone: '1'
```


or this

```
service: landroid_cloud.setzone
data:
  zone: 1
```

renders errors on 1.8.5 - please check you have the latest release installed

**Comment by Barma-lej** [comment]
You added a variable 'zone' [here](https://github.com/MTrab/landroid_cloud/commit/6c83f1fa170a710779568729037075ef08bcd2e3) but you don't use it...
I think you need also change lines **349** from `cli.setZone(call.data["zone"])` to `cli.setZone(zone)` and **351** from `client[0].setZone(call.data["zone"])` to `client[0].setZone(zone)`

**Comment by MTrab** [comment]
Ooooops :D Fix coming up :D

**Comment by MTrab** [comment]
And update ready

**Comment by infohannes** [comment]
Hello Morton and Barma-lej,
Many thanks for the quick processing.
Now it's working fine
5 Stars Support
